package com.hayden.hap.common.excel.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class ExcelTemplateItemVO extends BaseVO {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEMID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Long itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Long templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEM_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String item_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEM_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String item_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String main_func_code;
    private String func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.COLUMN_NO
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String column_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.COLUMN_TITLE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String column_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEM_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String item_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEM_LEN
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String item_len;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.ITEM_PRECISION
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String item_precision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.DEFAULT_VALUE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String default_value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.IS_PK
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Integer is_pk;
    
    private Integer is_enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.IS_MANDATORY
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Integer is_mandatory;
    private Integer is_notnull;//是否非空
   
    private String excel_cell_type;

  
    private Integer is_newlable_show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.VALUE_ITEM
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String query_sel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template_item.WHERE_ITEM
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String dict;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_excel_template_item
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public ExcelTemplateItemVO() {
        super("SY_EXCEL_TEMPLATE_ITEM");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEMID
     *
     * @return the value of sy_excel_template_item.ITEMID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Long getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEMID
     *
     * @param itemid the value for sy_excel_template_item.ITEMID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItemid(Long itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.TEMPLATEID
     *
     * @return the value of sy_excel_template_item.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Long getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.TEMPLATEID
     *
     * @param templateid the value for sy_excel_template_item.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setTemplateid(Long templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEM_CODE
     *
     * @return the value of sy_excel_template_item.ITEM_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getItem_code() {
        return item_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEM_CODE
     *
     * @param item_code the value for sy_excel_template_item.ITEM_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItem_code(String item_code) {
        this.item_code = item_code == null ? null : item_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEM_NAME
     *
     * @return the value of sy_excel_template_item.ITEM_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getItem_name() {
        return item_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEM_NAME
     *
     * @param item_name the value for sy_excel_template_item.ITEM_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItem_name(String item_name) {
        this.item_name = item_name == null ? null : item_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.FUNC_CODE
     *
     * @return the value of sy_excel_template_item.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.FUNC_CODE
     *
     * @param func_code the value for sy_excel_template_item.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.COLUMN_NO
     *
     * @return the value of sy_excel_template_item.COLUMN_NO
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getColumn_no() {
        return column_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.COLUMN_NO
     *
     * @param column_no the value for sy_excel_template_item.COLUMN_NO
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setColumn_no(String column_no) {
        this.column_no = column_no == null ? null : column_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.COLUMN_TITLE
     *
     * @return the value of sy_excel_template_item.COLUMN_TITLE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getColumn_title() {
        return column_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.COLUMN_TITLE
     *
     * @param column_title the value for sy_excel_template_item.COLUMN_TITLE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setColumn_title(String column_title) {
        this.column_title = column_title == null ? null : column_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEM_TYPE
     *
     * @return the value of sy_excel_template_item.ITEM_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getItem_type() {
        return item_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEM_TYPE
     *
     * @param item_type the value for sy_excel_template_item.ITEM_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItem_type(String item_type) {
        this.item_type = item_type == null ? null : item_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEM_LEN
     *
     * @return the value of sy_excel_template_item.ITEM_LEN
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getItem_len() {
        return item_len;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEM_LEN
     *
     * @param item_len the value for sy_excel_template_item.ITEM_LEN
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItem_len(String item_len) {
        this.item_len = item_len == null ? null : item_len.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.ITEM_PRECISION
     *
     * @return the value of sy_excel_template_item.ITEM_PRECISION
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getItem_precision() {
        return item_precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.ITEM_PRECISION
     *
     * @param item_precision the value for sy_excel_template_item.ITEM_PRECISION
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setItem_precision(String item_precision) {
        this.item_precision = item_precision == null ? null : item_precision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.DEFAULT_VALUE
     *
     * @return the value of sy_excel_template_item.DEFAULT_VALUE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getDefault_value() {
        return default_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.DEFAULT_VALUE
     *
     * @param default_value the value for sy_excel_template_item.DEFAULT_VALUE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setDefault_value(String default_value) {
        this.default_value = default_value == null ? null : default_value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.IS_PK
     *
     * @return the value of sy_excel_template_item.IS_PK
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Integer getIs_pk() {
        return is_pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.IS_PK
     *
     * @param is_pk the value for sy_excel_template_item.IS_PK
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setIs_pk(Integer is_pk) {
        this.is_pk = is_pk ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template_item.IS_MANDATORY
     *
     * @return the value of sy_excel_template_item.IS_MANDATORY
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Integer getIs_mandatory() {
        return is_mandatory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template_item.IS_MANDATORY
     *
     * @param is_mandatory the value for sy_excel_template_item.IS_MANDATORY
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    
    public void setIs_mandatory(Integer is_mandatory) {
        this.is_mandatory = is_mandatory;
    }

    public Integer getIs_notnull() {
		return is_notnull;
	}

	public void setIs_notnull(Integer is_notnull) {
		this.is_notnull = is_notnull;
	}

	public String getExcel_cell_type() {
		return excel_cell_type;
	}

	public void setExcel_cell_type(String excel_cell_type) {
		this.excel_cell_type = excel_cell_type;
	}

	public Integer getIs_newlable_show() {
		return is_newlable_show;
	}

	public void setIs_newlable_show(Integer is_newlable_show) {
		this.is_newlable_show = is_newlable_show;
	}

	public String getDict() {
		return dict;
	}

	public void setDict(String dict) {
		this.dict = dict;
	}

	public Integer getIs_enable() {
		return is_enable;
	}

	public void setIs_enable(Integer is_enable) {
		this.is_enable = is_enable;
	}

	public String getQuery_sel() {
		return query_sel;
	}

	public void setQuery_sel(String query_sel) {
		this.query_sel = query_sel;
	}

	public String getMain_func_code() {
		return main_func_code;
	}

	public void setMain_func_code(String main_func_code) {
		this.main_func_code = main_func_code;
	}
	
}