package com.hayden.hap.common.entity.perm;

import com.hayden.hap.dbop.entity.BaseVO;
import lombok.Data;

@Data
public class PermPackageItemVO extends BaseVO {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.item_id
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private Long item_id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.package_id
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private Long package_id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.package_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String package_code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.modulecode
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String modulecode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.func_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String func_code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.btn_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String btn_code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.is_custom_btn
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private Integer is_custom_btn;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.custom_btn_info
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String custom_btn_info;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.btn_type
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String btn_type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.order_index
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private Integer order_index;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_perm_package_item.opera_info
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	private String opera_info;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sy_perm_package_item
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public PermPackageItemVO() {
		super("SY_PERM_PACKAGE_ITEM");
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.package_code
	 *
	 * @param package_code
	 *            the value for sy_perm_package_item.package_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setPackage_code(String package_code) {
		this.package_code = package_code == null ? null : package_code.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.modulecode
	 *
	 * @param modulecode
	 *            the value for sy_perm_package_item.modulecode
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setModulecode(String modulecode) {
		this.modulecode = modulecode == null ? null : modulecode.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.func_code
	 *
	 * @param func_code
	 *            the value for sy_perm_package_item.func_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setFunc_code(String func_code) {
		this.func_code = func_code == null ? null : func_code.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.btn_code
	 *
	 * @param btn_code
	 *            the value for sy_perm_package_item.btn_code
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setBtn_code(String btn_code) {
		this.btn_code = btn_code == null ? null : btn_code.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.custom_btn_info
	 *
	 * @param custom_btn_info
	 *            the value for sy_perm_package_item.custom_btn_info
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setCustom_btn_info(String custom_btn_info) {
		this.custom_btn_info = custom_btn_info == null ? null : custom_btn_info.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.btn_type
	 *
	 * @param btn_type
	 *            the value for sy_perm_package_item.btn_type
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setBtn_type(String btn_type) {
		this.btn_type = btn_type == null ? null : btn_type.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_perm_package_item.opera_info
	 *
	 * @param opera_info
	 *            the value for sy_perm_package_item.opera_info
	 *
	 * @mbggenerated Thu May 10 15:22:56 CST 2018
	 */
	public void setOpera_info(String opera_info) {
		this.opera_info = opera_info == null ? null : opera_info.trim();
	}

	// ------------------func_name-----------------
	private String func_name;

    public void setFunc_name(String func_name) {
		this.func_name = func_name == null ? null : func_name.trim();
	}

	// ------------------func_name-----------------
	private String btn_name;

    public void setBtn_name(String btn_name) {
		this.btn_name = btn_name == null ? null : btn_name.trim();
	}
}