package com.hayden.hap.common.entity.perm;

import com.hayden.hap.dbop.entity.BaseVO;
import lombok.Data;

@Data
public class PermPackageVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.package_id
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private Long package_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.package_name
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String package_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.package_code
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String package_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.menu_code
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String menu_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.func_code_default
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String func_code_default;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.opera_info
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String opera_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.is_enable
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private Integer is_enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.order_index
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private Integer order_index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.summary
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.is_buy
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private Integer is_buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_perm_package.product_flag
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    private Integer product_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_perm_package
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public PermPackageVO() {
        super("sy_perm_package");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.package_name
     *
     * @param package_name the value for sy_perm_package.package_name
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setPackage_name(String package_name) {
        this.package_name = package_name == null ? null : package_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.package_code
     *
     * @param package_code the value for sy_perm_package.package_code
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setPackage_code(String package_code) {
        this.package_code = package_code == null ? null : package_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.menu_code
     *
     * @param menu_code the value for sy_perm_package.menu_code
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setMenu_code(String menu_code) {
        this.menu_code = menu_code == null ? null : menu_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.func_code_default
     *
     * @param func_code_default the value for sy_perm_package.func_code_default
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setFunc_code_default(String func_code_default) {
        this.func_code_default = func_code_default == null ? null : func_code_default.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.opera_info
     *
     * @param opera_info the value for sy_perm_package.opera_info
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setOpera_info(String opera_info) {
        this.opera_info = opera_info == null ? null : opera_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_perm_package.summary
     *
     * @param summary the value for sy_perm_package.summary
     *
     * @mbggenerated Thu Mar 14 15:56:22 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

}