package com.hayden.hap.common.func.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class FuncLinkDataVO extends BaseVO {
 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_id
     *
     * @mbggenerated
     */
    private Long ldata_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.func_code
     *
     * @mbggenerated
     */
    private String func_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.parent_table
     *
     * @mbggenerated
     */
    private String parent_table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.table_code
     *
     * @mbggenerated
     */
    private String table_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.table_name
     *
     * @mbggenerated
     */
    private String table_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_del
     *
     * @mbggenerated
     */
    private String ldata_del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_update
     *
     * @mbggenerated
     */
    private Integer ldata_update;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_where
     *
     * @mbggenerated
     */
    private String ldata_where;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.parent_fields
     *
     * @mbggenerated
     */
    private String parent_fields;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.parent_fields_name
     *
     * @mbggenerated
     */
    private String parent_fields_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.table_fields
     *
     * @mbggenerated
     */
    private String table_fields;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.table_fields_name
     *
     * @mbggenerated
     */
    private String table_fields_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_order
     *
     * @mbggenerated
     */
    private Integer ldata_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_isenable
     *
     * @mbggenerated
     */
    private Integer ldata_isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_data.ldata_comment
     *
     * @mbggenerated
     */
    private String ldata_comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_func_link_data
     *
     * @mbggenerated
     */
    public FuncLinkDataVO() {
        super("SY_FUNC_LINK_DATA");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_id
     *
     * @return the value of sy_func_link_data.ldata_id
     *
     * @mbggenerated
     */
    public Long getLdata_id() {
        return ldata_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_id
     *
     * @param ldata_id the value for sy_func_link_data.ldata_id
     *
     * @mbggenerated
     */
    public void setLdata_id(Long ldata_id) {
        this.ldata_id = ldata_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.tenantid
     *
     * @return the value of sy_func_link_data.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.tenantid
     *
     * @param tenantid the value for sy_func_link_data.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.func_code
     *
     * @return the value of sy_func_link_data.func_code
     *
     * @mbggenerated
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.func_code
     *
     * @param func_code the value for sy_func_link_data.func_code
     *
     * @mbggenerated
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.parent_table
     *
     * @return the value of sy_func_link_data.parent_table
     *
     * @mbggenerated
     */
    public String getParent_table() {
        return parent_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.parent_table
     *
     * @param parent_table the value for sy_func_link_data.parent_table
     *
     * @mbggenerated
     */
    public void setParent_table(String parent_table) {
        this.parent_table = parent_table == null ? null : parent_table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.table_code
     *
     * @return the value of sy_func_link_data.table_code
     *
     * @mbggenerated
     */
    public String getTable_code() {
        return table_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.table_code
     *
     * @param table_code the value for sy_func_link_data.table_code
     *
     * @mbggenerated
     */
    public void setTable_code(String table_code) {
        this.table_code = table_code == null ? null : table_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.table_name
     *
     * @return the value of sy_func_link_data.table_name
     *
     * @mbggenerated
     */
    public String getTable_name() {
        return table_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.table_name
     *
     * @param table_name the value for sy_func_link_data.table_name
     *
     * @mbggenerated
     */
    public void setTable_name(String table_name) {
        this.table_name = table_name == null ? null : table_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_del
     *
     * @return the value of sy_func_link_data.ldata_del
     *
     * @mbggenerated
     */
    public String getLdata_del() {
        return ldata_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_del
     *
     * @param ldata_del the value for sy_func_link_data.ldata_del
     *
     * @mbggenerated
     */
    public void setLdata_del(String ldata_del) {
        this.ldata_del = ldata_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_update
     *
     * @return the value of sy_func_link_data.ldata_update
     *
     * @mbggenerated
     */
    public Integer getLdata_update() {
        return ldata_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_update
     *
     * @param ldata_update the value for sy_func_link_data.ldata_update
     *
     * @mbggenerated
     */
    public void setLdata_update(Integer ldata_update) {
        this.ldata_update = ldata_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_where
     *
     * @return the value of sy_func_link_data.ldata_where
     *
     * @mbggenerated
     */
    public String getLdata_where() {
        return ldata_where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_where
     *
     * @param ldata_where the value for sy_func_link_data.ldata_where
     *
     * @mbggenerated
     */
    public void setLdata_where(String ldata_where) {
        this.ldata_where = ldata_where == null ? null : ldata_where.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.parent_fields
     *
     * @return the value of sy_func_link_data.parent_fields
     *
     * @mbggenerated
     */
    public String getParent_fields() {
        return parent_fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.parent_fields
     *
     * @param parent_fields the value for sy_func_link_data.parent_fields
     *
     * @mbggenerated
     */
    public void setParent_fields(String parent_fields) {
        this.parent_fields = parent_fields == null ? null : parent_fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.parent_fields_name
     *
     * @return the value of sy_func_link_data.parent_fields_name
     *
     * @mbggenerated
     */
    public String getParent_fields_name() {
        return parent_fields_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.parent_fields_name
     *
     * @param parent_fields_name the value for sy_func_link_data.parent_fields_name
     *
     * @mbggenerated
     */
    public void setParent_fields_name(String parent_fields_name) {
        this.parent_fields_name = parent_fields_name == null ? null : parent_fields_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.table_fields
     *
     * @return the value of sy_func_link_data.table_fields
     *
     * @mbggenerated
     */
    public String getTable_fields() {
        return table_fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.table_fields
     *
     * @param table_fields the value for sy_func_link_data.table_fields
     *
     * @mbggenerated
     */
    public void setTable_fields(String table_fields) {
        this.table_fields = table_fields == null ? null : table_fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.table_fields_name
     *
     * @return the value of sy_func_link_data.table_fields_name
     *
     * @mbggenerated
     */
    public String getTable_fields_name() {
        return table_fields_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.table_fields_name
     *
     * @param table_fields_name the value for sy_func_link_data.table_fields_name
     *
     * @mbggenerated
     */
    public void setTable_fields_name(String table_fields_name) {
        this.table_fields_name = table_fields_name == null ? null : table_fields_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_order
     *
     * @return the value of sy_func_link_data.ldata_order
     *
     * @mbggenerated
     */
    public Integer getLdata_order() {
        return ldata_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_order
     *
     * @param ldata_order the value for sy_func_link_data.ldata_order
     *
     * @mbggenerated
     */
    public void setLdata_order(Integer ldata_order) {
        this.ldata_order = ldata_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_isenable
     *
     * @return the value of sy_func_link_data.ldata_isenable
     *
     * @mbggenerated
     */
    public Integer getLdata_isenable() {
        return ldata_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_isenable
     *
     * @param ldata_isenable the value for sy_func_link_data.ldata_isenable
     *
     * @mbggenerated
     */
    public void setLdata_isenable(Integer ldata_isenable) {
        this.ldata_isenable = ldata_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_data.ldata_comment
     *
     * @return the value of sy_func_link_data.ldata_comment
     *
     * @mbggenerated
     */
    public String getLdata_comment() {
        return ldata_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_data.ldata_comment
     *
     * @param ldata_comment the value for sy_func_link_data.ldata_comment
     *
     * @mbggenerated
     */
    public void setLdata_comment(String ldata_comment) {
        this.ldata_comment = ldata_comment == null ? null : ldata_comment.trim();
    }
}