package com.hayden.hap.upgrade.entity;

import com.hayden.hap.dbop.entity.BaseVO;

public class UpgradeModuleVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.id
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.code
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.name
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.currentver
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String currentver;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.currentver
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String productver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.status
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.progress
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.person
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private String person;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private Long datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private Long lastfilets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    private Long prolastfilets;

    public Long getProlastfilets() {
        return prolastfilets;
    }

    public void setProlastfilets(Long prolastfilets) {
        this.prolastfilets = prolastfilets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mgr_upgrade_module
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public UpgradeModuleVO() {
        super("mgr_upgrade_module");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.id
     *
     * @return the value of mgr_upgrade_module.id
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.id
     *
     * @param id the value for mgr_upgrade_module.id
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.code
     *
     * @return the value of mgr_upgrade_module.code
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.code
     *
     * @param code the value for mgr_upgrade_module.code
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.name
     *
     * @return the value of mgr_upgrade_module.name
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.name
     *
     * @param name the value for mgr_upgrade_module.name
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.currentver
     *
     * @return the value of mgr_upgrade_module.currentver
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getCurrentver() {
        return currentver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.currentver
     *
     * @param currentver the value for mgr_upgrade_module.currentver
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setCurrentver(String currentver) {
        this.currentver = currentver == null ? null : currentver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.status
     *
     * @return the value of mgr_upgrade_module.status
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.status
     *
     * @param status the value for mgr_upgrade_module.status
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.progress
     *
     * @return the value of mgr_upgrade_module.progress
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.progress
     *
     * @param progress the value for mgr_upgrade_module.progress
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.person
     *
     * @return the value of mgr_upgrade_module.person
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.person
     *
     * @param person the value for mgr_upgrade_module.person
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.datetime
     *
     * @return the value of mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public Long getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.datetime
     *
     * @param datetime the value for mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setDatetime(Long datetime) {
        this.datetime = datetime ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_module.datetime
     *
     * @return the value of mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public Long getLastfilets() {
        return lastfilets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_module.datetime
     *
     * @param lastfilets the value for mgr_upgrade_module.datetime
     *
     * @mbggenerated Fri Jun 05 14:16:47 CST 2020
     */
    public void setLastfilets(Long lastfilets) {
        this.lastfilets = lastfilets ;
    }

    public String getProductver() {
        return productver;
    }

    public void setProductver(String productver) {
        this.productver = productver;
    }
}