package com.hayden.hap.common.excel.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class ExcelTemplateVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Long templateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.TEMP_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String temp_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.TEMP_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String temp_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String file_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.SMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String smarker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.EMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String emarker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.ISUPDATE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String isupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.PRE_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String pre_class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.SUP_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private String sup_class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_excel_template.ATTACHMENT
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    private Integer attachment;
    private Integer is_import_linklist;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_excel_template
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public ExcelTemplateVO() {
        super("SY_EXCEL_TEMPLATE");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.TEMPLATEID
     *
     * @return the value of sy_excel_template.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Long getTemplateid() {
        return templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.TEMPLATEID
     *
     * @param templateid the value for sy_excel_template.TEMPLATEID
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setTemplateid(Long templateid) {
        this.templateid = templateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.TEMP_CODE
     *
     * @return the value of sy_excel_template.TEMP_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getTemp_code() {
        return temp_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.TEMP_CODE
     *
     * @param temp_code the value for sy_excel_template.TEMP_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setTemp_code(String temp_code) {
        this.temp_code = temp_code == null ? null : temp_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.TEMP_NAME
     *
     * @return the value of sy_excel_template.TEMP_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getTemp_name() {
        return temp_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.TEMP_NAME
     *
     * @param temp_name the value for sy_excel_template.TEMP_NAME
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setTemp_name(String temp_name) {
        this.temp_name = temp_name == null ? null : temp_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.FUNC_CODE
     *
     * @return the value of sy_excel_template.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.FUNC_CODE
     *
     * @param func_code the value for sy_excel_template.FUNC_CODE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.FILE_TYPE
     *
     * @return the value of sy_excel_template.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getFile_type() {
        return file_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.FILE_TYPE
     *
     * @param file_type the value for sy_excel_template.FILE_TYPE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setFile_type(String file_type) {
        this.file_type = file_type == null ? null : file_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.SMARKER
     *
     * @return the value of sy_excel_template.SMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getSmarker() {
        return smarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.SMARKER
     *
     * @param smarker the value for sy_excel_template.SMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setSmarker(String smarker) {
        this.smarker = smarker == null ? null : smarker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.EMARKER
     *
     * @return the value of sy_excel_template.EMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getEmarker() {
        return emarker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.EMARKER
     *
     * @param emarker the value for sy_excel_template.EMARKER
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setEmarker(String emarker) {
        this.emarker = emarker == null ? null : emarker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.ISUPDATE
     *
     * @return the value of sy_excel_template.ISUPDATE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getIsupdate() {
        return isupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.ISUPDATE
     *
     * @param isupdate the value for sy_excel_template.ISUPDATE
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setIsupdate(String isupdate) {
        this.isupdate = isupdate == null ? null : isupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.PRE_CLASS
     *
     * @return the value of sy_excel_template.PRE_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getPre_class() {
        return pre_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.PRE_CLASS
     *
     * @param pre_class the value for sy_excel_template.PRE_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setPre_class(String pre_class) {
        this.pre_class = pre_class == null ? null : pre_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.SUP_CLASS
     *
     * @return the value of sy_excel_template.SUP_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public String getSup_class() {
        return sup_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.SUP_CLASS
     *
     * @param sup_class the value for sy_excel_template.SUP_CLASS
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setSup_class(String sup_class) {
        this.sup_class = sup_class == null ? null : sup_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_excel_template.ATTACHMENT
     *
     * @return the value of sy_excel_template.ATTACHMENT
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public Integer getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_excel_template.ATTACHMENT
     *
     * @param attachment the value for sy_excel_template.ATTACHMENT
     *
     * @mbggenerated Mon Apr 11 16:21:18 CST 2016
     */
    public void setAttachment(Integer attachment) {
        this.attachment = attachment;
    }

	public Integer getIs_import_linklist() {
		return is_import_linklist;
	}

	public void setIs_import_linklist(Integer is_import_linklist) {
		this.is_import_linklist = is_import_linklist;
	}
    
}