package com.hayden.hap.common.entity.form;

import com.hayden.hap.dbop.entity.BaseVO;

public class FormConditionDetailVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.id
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.condition_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String condition_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.condition_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String condition_info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.form_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String form_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.group_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String group_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.fitem_codes
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String fitem_codes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition_detail.fitem_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    private String fitem_info;

    private String condition_value;

    public String getCondition_value() {
        return condition_value;
    }

    public void setCondition_value(String condition_value) {
        this.condition_value = condition_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_form_condition_detail
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public FormConditionDetailVO() {
        super("sy_form_condition_detail");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.id
     *
     * @return the value of sy_form_condition_detail.id
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.id
     *
     * @param id the value for sy_form_condition_detail.id
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.condition_code
     *
     * @return the value of sy_form_condition_detail.condition_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getCondition_code() {
        return condition_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.condition_code
     *
     * @param condition_code the value for sy_form_condition_detail.condition_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setCondition_code(String condition_code) {
        this.condition_code = condition_code == null ? null : condition_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.condition_info
     *
     * @return the value of sy_form_condition_detail.condition_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getCondition_info() {
        return condition_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.condition_info
     *
     * @param condition_info the value for sy_form_condition_detail.condition_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setCondition_info(String condition_info) {
        this.condition_info = condition_info == null ? null : condition_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.form_code
     *
     * @return the value of sy_form_condition_detail.form_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getForm_code() {
        return form_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.form_code
     *
     * @param form_code the value for sy_form_condition_detail.form_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setForm_code(String form_code) {
        this.form_code = form_code == null ? null : form_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.group_code
     *
     * @return the value of sy_form_condition_detail.group_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.group_code
     *
     * @param group_code the value for sy_form_condition_detail.group_code
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.fitem_codes
     *
     * @return the value of sy_form_condition_detail.fitem_codes
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getFitem_codes() {
        return fitem_codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.fitem_codes
     *
     * @param fitem_codes the value for sy_form_condition_detail.fitem_codes
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setFitem_codes(String fitem_codes) {
        this.fitem_codes = fitem_codes == null ? null : fitem_codes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition_detail.fitem_info
     *
     * @return the value of sy_form_condition_detail.fitem_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public String getFitem_info() {
        return fitem_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition_detail.fitem_info
     *
     * @param fitem_info the value for sy_form_condition_detail.fitem_info
     *
     * @mbggenerated Mon Jun 07 11:34:33 CST 2021
     */
    public void setFitem_info(String fitem_info) {
        this.fitem_info = fitem_info == null ? null : fitem_info.trim();
    }
}