package com.hayden.hap.common.entity.form;

import com.hayden.hap.dbop.entity.BaseVO;

import java.util.List;

public class FormQueryVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private Long fquery_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.func_code
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private String func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_name
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private String fquery_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_isdefault
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private Integer fquery_isdefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fconf_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private Long fconf_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_ispublic
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private Integer fquery_ispublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_sql
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private String fquery_sql;
    
    private List<FormQueryItemVO> fquery_sql_arr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_sql_ch
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private String fquery_sql_ch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_order
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private Integer fquery_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_query.fquery_memo
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    private String fquery_memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_form_query
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public FormQueryVO() {
        super("SY_FORM_QUERY");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_id
     *
     * @return the value of sy_form_query.fquery_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public Long getFquery_id() {
        return fquery_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_id
     *
     * @param fquery_id the value for sy_form_query.fquery_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_id(Long fquery_id) {
        this.fquery_id = fquery_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.func_code
     *
     * @return the value of sy_form_query.func_code
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.func_code
     *
     * @param func_code the value for sy_form_query.func_code
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_name
     *
     * @return the value of sy_form_query.fquery_name
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public String getFquery_name() {
        return fquery_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_name
     *
     * @param fquery_name the value for sy_form_query.fquery_name
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_name(String fquery_name) {
        this.fquery_name = fquery_name == null ? null : fquery_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_isdefault
     *
     * @return the value of sy_form_query.fquery_isdefault
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public Integer getFquery_isdefault() {
        return fquery_isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_isdefault
     *
     * @param fquery_isdefault the value for sy_form_query.fquery_isdefault
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_isdefault(Integer fquery_isdefault) {
        this.fquery_isdefault = fquery_isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fconf_id
     *
     * @return the value of sy_form_query.fconf_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public Long getFconf_id() {
        return fconf_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fconf_id
     *
     * @param fconf_id the value for sy_form_query.fconf_id
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFconf_id(Long fconf_id) {
        this.fconf_id = fconf_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_ispublic
     *
     * @return the value of sy_form_query.fquery_ispublic
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public Integer getFquery_ispublic() {
        return fquery_ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_ispublic
     *
     * @param fquery_ispublic the value for sy_form_query.fquery_ispublic
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_ispublic(Integer fquery_ispublic) {
        this.fquery_ispublic = fquery_ispublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_sql
     *
     * @return the value of sy_form_query.fquery_sql
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public String getFquery_sql() {
        return fquery_sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_sql
     *
     * @param fquery_sql the value for sy_form_query.fquery_sql
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_sql(String fquery_sql) {
        this.fquery_sql = fquery_sql == null ? null : fquery_sql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_sql_ch
     *
     * @return the value of sy_form_query.fquery_sql_ch
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public String getFquery_sql_ch() {
        return fquery_sql_ch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_sql_ch
     *
     * @param fquery_sql_ch the value for sy_form_query.fquery_sql_ch
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_sql_ch(String fquery_sql_ch) {
        this.fquery_sql_ch = fquery_sql_ch == null ? null : fquery_sql_ch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_order
     *
     * @return the value of sy_form_query.fquery_order
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public Integer getFquery_order() {
        return fquery_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_order
     *
     * @param fquery_order the value for sy_form_query.fquery_order
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_order(Integer fquery_order) {
        this.fquery_order = fquery_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_query.fquery_memo
     *
     * @return the value of sy_form_query.fquery_memo
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public String getFquery_memo() {
        return fquery_memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_query.fquery_memo
     *
     * @param fquery_memo the value for sy_form_query.fquery_memo
     *
     * @mbggenerated Thu Mar 17 10:56:29 CST 2016
     */
    public void setFquery_memo(String fquery_memo) {
        this.fquery_memo = fquery_memo == null ? null : fquery_memo.trim();
    }

	public List<FormQueryItemVO> getFquery_sql_arr() {
		return fquery_sql_arr;
	}

	public void setFquery_sql_arr(List<FormQueryItemVO> fquery_sql_arr) {
		this.fquery_sql_arr = fquery_sql_arr;
	}
}