package com.hayden.hap.common.entity.form;


/**
 * 移动端表单VO
 * @author zhangfeng
 * @date 2018年1月23日
 */
public class FormMVO extends FormVO{

	private static final long serialVersionUID = 1L;

	public FormMVO() {
		super("SY_FORM_MOBILE");
	}

	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.formid
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Long formid;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.modulecode
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String modulecode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.form_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String form_code;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.form_name
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String form_name;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.opera_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String opera_table_code;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.query_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String query_table_code;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.card_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer card_num;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.where_str
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String where_str;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.quick_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String quick_order;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.extends_class
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String extends_class;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.page_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer page_num;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.form_comment
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String form_comment;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.product_flag
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String product_flag;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.is_validate_consistency
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer is_validate_consistency;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.is_buy
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer is_buy;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.common_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private String common_order;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.form_title_width
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer form_title_width;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.is_search_support
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer is_search_support;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_form_mobile.is_pro_search
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   private Integer is_pro_search;

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.formid
    *
    * @return the value of sy_form_mobile.formid
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Long getFormid() {
       return formid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.formid
    *
    * @param formid the value for sy_form_mobile.formid
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setFormid(Long formid) {
       this.formid = formid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.modulecode
    *
    * @return the value of sy_form_mobile.modulecode
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getModulecode() {
       return modulecode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.modulecode
    *
    * @param modulecode the value for sy_form_mobile.modulecode
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setModulecode(String modulecode) {
       this.modulecode = modulecode == null ? null : modulecode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.form_code
    *
    * @return the value of sy_form_mobile.form_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getForm_code() {
       return form_code;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.form_code
    *
    * @param form_code the value for sy_form_mobile.form_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setForm_code(String form_code) {
       this.form_code = form_code == null ? null : form_code.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.form_name
    *
    * @return the value of sy_form_mobile.form_name
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getForm_name() {
       return form_name;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.form_name
    *
    * @param form_name the value for sy_form_mobile.form_name
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setForm_name(String form_name) {
       this.form_name = form_name == null ? null : form_name.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.opera_table_code
    *
    * @return the value of sy_form_mobile.opera_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getOpera_table_code() {
       return opera_table_code;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.opera_table_code
    *
    * @param opera_table_code the value for sy_form_mobile.opera_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setOpera_table_code(String opera_table_code) {
       this.opera_table_code = opera_table_code == null ? null : opera_table_code.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.query_table_code
    *
    * @return the value of sy_form_mobile.query_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getQuery_table_code() {
       return query_table_code;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.query_table_code
    *
    * @param query_table_code the value for sy_form_mobile.query_table_code
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setQuery_table_code(String query_table_code) {
       this.query_table_code = query_table_code == null ? null : query_table_code.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.card_num
    *
    * @return the value of sy_form_mobile.card_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getCard_num() {
       return card_num;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.card_num
    *
    * @param card_num the value for sy_form_mobile.card_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setCard_num(Integer card_num) {
       this.card_num = card_num;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.where_str
    *
    * @return the value of sy_form_mobile.where_str
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getWhere_str() {
       return where_str;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.where_str
    *
    * @param where_str the value for sy_form_mobile.where_str
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setWhere_str(String where_str) {
       this.where_str = where_str == null ? null : where_str.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.quick_order
    *
    * @return the value of sy_form_mobile.quick_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getQuick_order() {
       return quick_order;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.quick_order
    *
    * @param quick_order the value for sy_form_mobile.quick_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setQuick_order(String quick_order) {
       this.quick_order = quick_order == null ? null : quick_order.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.extends_class
    *
    * @return the value of sy_form_mobile.extends_class
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getExtends_class() {
       return extends_class;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.extends_class
    *
    * @param extends_class the value for sy_form_mobile.extends_class
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setExtends_class(String extends_class) {
       this.extends_class = extends_class == null ? null : extends_class.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.page_num
    *
    * @return the value of sy_form_mobile.page_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getPage_num() {
       return page_num;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.page_num
    *
    * @param page_num the value for sy_form_mobile.page_num
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setPage_num(Integer page_num) {
       this.page_num = page_num;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.form_comment
    *
    * @return the value of sy_form_mobile.form_comment
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getForm_comment() {
       return form_comment;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.form_comment
    *
    * @param form_comment the value for sy_form_mobile.form_comment
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setForm_comment(String form_comment) {
       this.form_comment = form_comment == null ? null : form_comment.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.product_flag
    *
    * @return the value of sy_form_mobile.product_flag
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getProduct_flag() {
       return product_flag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.product_flag
    *
    * @param product_flag the value for sy_form_mobile.product_flag
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setProduct_flag(String product_flag) {
       this.product_flag = product_flag;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.is_validate_consistency
    *
    * @return the value of sy_form_mobile.is_validate_consistency
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getIs_validate_consistency() {
       return is_validate_consistency;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.is_validate_consistency
    *
    * @param is_validate_consistency the value for sy_form_mobile.is_validate_consistency
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setIs_validate_consistency(Integer is_validate_consistency) {
       this.is_validate_consistency = is_validate_consistency;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.is_buy
    *
    * @return the value of sy_form_mobile.is_buy
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getIs_buy() {
       return is_buy;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.is_buy
    *
    * @param is_buy the value for sy_form_mobile.is_buy
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setIs_buy(Integer is_buy) {
       this.is_buy = is_buy;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.common_order
    *
    * @return the value of sy_form_mobile.common_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public String getCommon_order() {
       return common_order;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.common_order
    *
    * @param common_order the value for sy_form_mobile.common_order
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setCommon_order(String common_order) {
       this.common_order = common_order == null ? null : common_order.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.form_title_width
    *
    * @return the value of sy_form_mobile.form_title_width
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getForm_title_width() {
       return form_title_width;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.form_title_width
    *
    * @param form_title_width the value for sy_form_mobile.form_title_width
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setForm_title_width(Integer form_title_width) {
       this.form_title_width = form_title_width;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.is_search_support
    *
    * @return the value of sy_form_mobile.is_search_support
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getIs_search_support() {
       return is_search_support;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.is_search_support
    *
    * @param is_search_support the value for sy_form_mobile.is_search_support
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setIs_search_support(Integer is_search_support) {
       this.is_search_support = is_search_support;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column sy_form_mobile.is_pro_search
    *
    * @return the value of sy_form_mobile.is_pro_search
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public Integer getIs_pro_search() {
       return is_pro_search;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column sy_form_mobile.is_pro_search
    *
    * @param is_pro_search the value for sy_form_mobile.is_pro_search
    *
    * @mbggenerated Wed May 09 11:20:16 CST 2018
    */
   public void setIs_pro_search(Integer is_pro_search) {
       this.is_pro_search = is_pro_search;
   }
}
