package com.hayden.hap.common.export.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class ExportTemplateItemVO extends BaseVO {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.expotritemid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private Long expotritemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.exportid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private Long exportid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.export_item_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private String export_item_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.export_item_name
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private String export_item_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.func_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private String func_code;
    private String main_func_code;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.column_no
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private Integer column_no;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.column_title
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private String column_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.is_display
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private Integer is_display;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.source_table
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private String item_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template_item.product_flag
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    private Integer product_flag;
    private String dateformat;

    public String getDateformat() {
		return dateformat;
	}

	public void setDateformat(String dateformat) {
		this.dateformat = dateformat;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_export_template_item
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public ExportTemplateItemVO() {
        super("SY_EXPORT_TEMPLATE_ITEM");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.expotritemid
     *
     * @return the value of sy_export_template_item.expotritemid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public Long getExpotritemid() {
        return expotritemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.expotritemid
     *
     * @param expotritemid the value for sy_export_template_item.expotritemid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setExpotritemid(Long expotritemid) {
        this.expotritemid = expotritemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.exportid
     *
     * @return the value of sy_export_template_item.exportid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public Long getExportid() {
        return exportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.exportid
     *
     * @param exportid the value for sy_export_template_item.exportid
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setExportid(Long exportid) {
        this.exportid = exportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.export_item_code
     *
     * @return the value of sy_export_template_item.export_item_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public String getExport_item_code() {
        return export_item_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.export_item_code
     *
     * @param export_item_code the value for sy_export_template_item.export_item_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setExport_item_code(String export_item_code) {
        this.export_item_code = export_item_code == null ? null : export_item_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.export_item_name
     *
     * @return the value of sy_export_template_item.export_item_name
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public String getExport_item_name() {
        return export_item_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.export_item_name
     *
     * @param export_item_name the value for sy_export_template_item.export_item_name
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setExport_item_name(String export_item_name) {
        this.export_item_name = export_item_name == null ? null : export_item_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.func_code
     *
     * @return the value of sy_export_template_item.func_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.func_code
     *
     * @param func_code the value for sy_export_template_item.func_code
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.column_no
     *
     * @return the value of sy_export_template_item.column_no
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public Integer getColumn_no() {
        return column_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.column_no
     *
     * @param column_no the value for sy_export_template_item.column_no
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setColumn_no(Integer column_no) {
        this.column_no = column_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.column_title
     *
     * @return the value of sy_export_template_item.column_title
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public String getColumn_title() {
        return column_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.column_title
     *
     * @param column_title the value for sy_export_template_item.column_title
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setColumn_title(String column_title) {
        this.column_title = column_title == null ? null : column_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.is_display
     *
     * @return the value of sy_export_template_item.is_display
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public Integer getIs_display() {
        return is_display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.is_display
     *
     * @param is_display the value for sy_export_template_item.is_display
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setIs_display(Integer is_display) {
        this.is_display = is_display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.item_type
     *
     * @return the value of sy_export_template_item.item_type
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public String getItem_type() {
        return item_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.item_type
     *
     * @param source_table the value for sy_export_template_item.item_type
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setItem_type(String item_type) {
        this.item_type = item_type == null ? null : item_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template_item.product_flag
     *
     * @return the value of sy_export_template_item.product_flag
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template_item.product_flag
     *
     * @param product_flag the value for sy_export_template_item.product_flag
     *
     * @mbggenerated Wed Sep 14 13:30:37 CST 2016
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }

	public String getMain_func_code() {
		return main_func_code;
	}

	public void setMain_func_code(String main_func_code) {
		this.main_func_code = main_func_code;
	}
    
    
}