package com.hayden.hap.common.export.entity;

import com.hayden.hap.common.common.entity.BaseVO;

import java.util.Date;

public class ExportHandleRecordVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.handle_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Long handle_id;
    private Long org_id;
    private double progress;

    private String dynamic_param;
 
    

	public double getProgress() {
		return progress;
	}

	public void setProgress(double progress) {
		this.progress = progress;
	}

	public Long getOrg_id() {
		return org_id;
	}

	public void setOrg_id(Long org_id) {
		this.org_id = org_id;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.module_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String module_code;

    private String export_user_name;
    
    public String getExport_user_name() {
		return export_user_name;
	}

	public void setExport_user_name(String export_user_name) {
		this.export_user_name = export_user_name;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.func_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.handle_query_param
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String handle_query_param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.export_user
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Long export_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.state
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.start_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Date start_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.end_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Date end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.attach
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String attach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.result
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.attach_type
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private String attach_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.import_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Long import_template_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.end_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Integer end_rows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.start_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Integer start_rows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_export_handle_record.export_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    private Long export_template_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pub_export_handle_record
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public ExportHandleRecordVO() {
        super("pub_export_handle_record");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.handle_id
     *
     * @return the value of pub_export_handle_record.handle_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Long getHandle_id() {
        return handle_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.handle_id
     *
     * @param handle_id the value for pub_export_handle_record.handle_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setHandle_id(Long handle_id) {
        this.handle_id = handle_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.module_code
     *
     * @return the value of pub_export_handle_record.module_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getModule_code() {
        return module_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.module_code
     *
     * @param module_code the value for pub_export_handle_record.module_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setModule_code(String module_code) {
        this.module_code = module_code == null ? null : module_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.func_code
     *
     * @return the value of pub_export_handle_record.func_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.func_code
     *
     * @param func_code the value for pub_export_handle_record.func_code
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.handle_query_param
     *
     * @return the value of pub_export_handle_record.handle_query_param
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getHandle_query_param() {
        return handle_query_param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.handle_query_param
     *
     * @param handle_query_param the value for pub_export_handle_record.handle_query_param
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setHandle_query_param(String handle_query_param) {
        this.handle_query_param = handle_query_param == null ? null : handle_query_param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.export_user
     *
     * @return the value of pub_export_handle_record.export_user
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Long getExport_user() {
        return export_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.export_user
     *
     * @param export_user the value for pub_export_handle_record.export_user
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setExport_user(Long export_user) {
        this.export_user = export_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.state
     *
     * @return the value of pub_export_handle_record.state
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.state
     *
     * @param state the value for pub_export_handle_record.state
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.start_time
     *
     * @return the value of pub_export_handle_record.start_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Date getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.start_time
     *
     * @param start_time the value for pub_export_handle_record.start_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setStart_time(Date start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.end_time
     *
     * @return the value of pub_export_handle_record.end_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Date getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.end_time
     *
     * @param end_time the value for pub_export_handle_record.end_time
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setEnd_time(Date end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.attach
     *
     * @return the value of pub_export_handle_record.attach
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.attach
     *
     * @param attach the value for pub_export_handle_record.attach
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.result
     *
     * @return the value of pub_export_handle_record.result
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.result
     *
     * @param result the value for pub_export_handle_record.result
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.attach_type
     *
     * @return the value of pub_export_handle_record.attach_type
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public String getAttach_type() {
        return attach_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.attach_type
     *
     * @param attach_type the value for pub_export_handle_record.attach_type
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setAttach_type(String attach_type) {
        this.attach_type = attach_type == null ? null : attach_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.import_template_id
     *
     * @return the value of pub_export_handle_record.import_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Long getImport_template_id() {
        return import_template_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.import_template_id
     *
     * @param import_template_id the value for pub_export_handle_record.import_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setImport_template_id(Long import_template_id) {
        this.import_template_id = import_template_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.end_rows
     *
     * @return the value of pub_export_handle_record.end_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Integer getEnd_rows() {
        return end_rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.end_rows
     *
     * @param end_rows the value for pub_export_handle_record.end_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setEnd_rows(Integer end_rows) {
        this.end_rows = end_rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.start_rows
     *
     * @return the value of pub_export_handle_record.start_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Integer getStart_rows() {
        return start_rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.start_rows
     *
     * @param start_rows the value for pub_export_handle_record.start_rows
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setStart_rows(Integer start_rows) {
        this.start_rows = start_rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_export_handle_record.export_template_id
     *
     * @return the value of pub_export_handle_record.export_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public Long getExport_template_id() {
        return export_template_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_export_handle_record.export_template_id
     *
     * @param export_template_id the value for pub_export_handle_record.export_template_id
     *
     * @mbggenerated Fri Apr 24 09:29:51 CST 2020
     */
    public void setExport_template_id(Long export_template_id) {
        this.export_template_id = export_template_id;
    }

    public String getDynamic_param() {
        return dynamic_param;
    }

    public void setDynamic_param(String dynamic_param) {
        this.dynamic_param = dynamic_param;
    }
}