package com.hayden.hap.common.entity.func;

import com.hayden.hap.dbop.entity.BaseVO;

public class FuncLinkItemMVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Long litem_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String main_func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String sub_func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_main_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String litem_main_field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_sub_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String litem_sub_field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_iswhere
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer litem_iswhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_query_sign
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String litem_query_sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_isvalue
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer litem_isvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_isconstant
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer litem_isconstant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.litem_comment
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String litem_comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_item_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer product_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_func_link_item_mobile
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public FuncLinkItemMVO() {
        super("sy_func_link_item_mobile");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_id
     *
     * @return the value of sy_func_link_item_mobile.litem_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Long getLitem_id() {
        return litem_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_id
     *
     * @param litem_id the value for sy_func_link_item_mobile.litem_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_id(Long litem_id) {
        this.litem_id = litem_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.main_func_code
     *
     * @return the value of sy_func_link_item_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getMain_func_code() {
        return main_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.main_func_code
     *
     * @param main_func_code the value for sy_func_link_item_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setMain_func_code(String main_func_code) {
        this.main_func_code = main_func_code == null ? null : main_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.sub_func_code
     *
     * @return the value of sy_func_link_item_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getSub_func_code() {
        return sub_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.sub_func_code
     *
     * @param sub_func_code the value for sy_func_link_item_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setSub_func_code(String sub_func_code) {
        this.sub_func_code = sub_func_code == null ? null : sub_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_main_field
     *
     * @return the value of sy_func_link_item_mobile.litem_main_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLitem_main_field() {
        return litem_main_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_main_field
     *
     * @param litem_main_field the value for sy_func_link_item_mobile.litem_main_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_main_field(String litem_main_field) {
        this.litem_main_field = litem_main_field == null ? null : litem_main_field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_sub_field
     *
     * @return the value of sy_func_link_item_mobile.litem_sub_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLitem_sub_field() {
        return litem_sub_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_sub_field
     *
     * @param litem_sub_field the value for sy_func_link_item_mobile.litem_sub_field
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_sub_field(String litem_sub_field) {
        this.litem_sub_field = litem_sub_field == null ? null : litem_sub_field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_iswhere
     *
     * @return the value of sy_func_link_item_mobile.litem_iswhere
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLitem_iswhere() {
        return litem_iswhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_iswhere
     *
     * @param litem_iswhere the value for sy_func_link_item_mobile.litem_iswhere
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_iswhere(Integer litem_iswhere) {
        this.litem_iswhere = litem_iswhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_query_sign
     *
     * @return the value of sy_func_link_item_mobile.litem_query_sign
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLitem_query_sign() {
        return litem_query_sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_query_sign
     *
     * @param litem_query_sign the value for sy_func_link_item_mobile.litem_query_sign
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_query_sign(String litem_query_sign) {
        this.litem_query_sign = litem_query_sign == null ? null : litem_query_sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_isvalue
     *
     * @return the value of sy_func_link_item_mobile.litem_isvalue
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLitem_isvalue() {
        return litem_isvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_isvalue
     *
     * @param litem_isvalue the value for sy_func_link_item_mobile.litem_isvalue
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_isvalue(Integer litem_isvalue) {
        this.litem_isvalue = litem_isvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_isconstant
     *
     * @return the value of sy_func_link_item_mobile.litem_isconstant
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLitem_isconstant() {
        return litem_isconstant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_isconstant
     *
     * @param litem_isconstant the value for sy_func_link_item_mobile.litem_isconstant
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_isconstant(Integer litem_isconstant) {
        this.litem_isconstant = litem_isconstant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.litem_comment
     *
     * @return the value of sy_func_link_item_mobile.litem_comment
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLitem_comment() {
        return litem_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.litem_comment
     *
     * @param litem_comment the value for sy_func_link_item_mobile.litem_comment
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLitem_comment(String litem_comment) {
        this.litem_comment = litem_comment == null ? null : litem_comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_item_mobile.product_flag
     *
     * @return the value of sy_func_link_item_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_item_mobile.product_flag
     *
     * @param product_flag the value for sy_func_link_item_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }
}