package com.hayden.hap.common.entity.func;

import com.hayden.hap.dbop.entity.BaseVO;

public class FuncVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.funcid
     *
     * @mbggenerated
     */
    private Long funcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.modulecode
     *
     * @mbggenerated
     */
    private String modulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_code
     *
     * @mbggenerated
     */
    private String func_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_name
     *
     * @mbggenerated
     */
    private String func_name;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_isenable
     *
     * @mbggenerated
     */
    private Integer func_isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_type
     *
     * @mbggenerated
     */
    private String func_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_acl_flag
     *
     * @mbggenerated
     */
    private Integer func_acl_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_action_falg
     *
     * @mbggenerated
     */
    private Integer func_action_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_session_flag
     *
     * @mbggenerated
     */
    private Integer func_session_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_readonly
     *
     * @mbggenerated
     */
    private Integer func_readonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_readonly_exp
     *
     * @mbggenerated
     */
    private String func_readonly_exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_delete_exp
     *
     * @mbggenerated
     */
    private String func_delete_exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_where
     *
     * @mbggenerated
     */
    private String func_where;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_info
     *
     * @mbggenerated
     */
    private String func_info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_param
     *
     * @mbggenerated
     */
    private String func_param;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_comment
     *
     * @mbggenerated
     */
    private String func_comment;
    
    /**
     * 挂接的工作流类型
     */
    private String func_wf_link_proctype;
    
    /**
     * 审核结束后允许的操作
     */
    private String func_wf_finish_allow;
    
    
    /**
     * 审批流待办的推送
     */
    private String func_wf_task_push;
    
    /**
     * 审批流提醒的推送
     */
    private String func_wf_remind_push;
    
    /**
     * func_isbuy:TODO(是否购买).
     */
    private Integer func_isbuy; 
    
    /**
     * 绑定源pc功能
     */
    private String func_pc_code;
    
    /**
     * 对应移动端功能
     */
    private String func_mobile_code;
    
    /**
     * 功能布局类型
     */
    private Integer func_layout;
    
    /**
     * 是否初始加载数据
     */
    private Integer func_isinit;
    
    /**
     * 功能版本号
     * 用于结构数据缓存策略
     */
    private String func_version;

    public Integer getFunc_isbuy() {
		return func_isbuy;
	}

	public void setFunc_isbuy(Integer func_isbuy) {
		this.func_isbuy = func_isbuy;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_func
     *
     * @mbggenerated
     */
    public FuncVO(String tableName) {
        super(tableName);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.funcid
     *
     * @return the value of sy_func.funcid
     *
     * @mbggenerated
     */
    public Long getFuncid() {
        return funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.funcid
     *
     * @param funcid the value for sy_func.funcid
     *
     * @mbggenerated
     */
    public void setFuncid(Long funcid) {
        this.funcid = funcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.tenantid
     *
     * @return the value of sy_func.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.tenantid
     *
     * @param tenantid the value for sy_func.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.modulecode
     *
     * @return the value of sy_func.modulecode
     *
     * @mbggenerated
     */
    public String getModulecode() {
        return modulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.modulecode
     *
     * @param modulecode the value for sy_func.modulecode
     *
     * @mbggenerated
     */
    public void setModulecode(String modulecode) {
        this.modulecode = modulecode == null ? null : modulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_code
     *
     * @return the value of sy_func.func_code
     *
     * @mbggenerated
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_code
     *
     * @param func_code the value for sy_func.func_code
     *
     * @mbggenerated
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_name
     *
     * @return the value of sy_func.func_name
     *
     * @mbggenerated
     */
    public String getFunc_name() {
        return func_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_name
     *
     * @param func_name the value for sy_func.func_name
     *
     * @mbggenerated
     */
    public void setFunc_name(String func_name) {
        this.func_name = func_name == null ? null : func_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_isenable
     *
     * @return the value of sy_func.func_isenable
     *
     * @mbggenerated
     */
    public Integer getFunc_isenable() {
        return func_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_isenable
     *
     * @param func_isenable the value for sy_func.func_isenable
     *
     * @mbggenerated
     */
    public void setFunc_isenable(Integer func_isenable) {
        this.func_isenable = func_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_type
     *
     * @return the value of sy_func.func_type
     *
     * @mbggenerated
     */
    public String getFunc_type() {
        return func_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_type
     *
     * @param func_type the value for sy_func.func_type
     *
     * @mbggenerated
     */
    public void setFunc_type(String func_type) {
        this.func_type = func_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_acl_flag
     *
     * @return the value of sy_func.func_acl_flag
     *
     * @mbggenerated
     */
    public Integer getFunc_acl_flag() {
        return func_acl_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_acl_flag
     *
     * @param func_acl_flag the value for sy_func.func_acl_flag
     *
     * @mbggenerated
     */
    public void setFunc_acl_flag(Integer func_acl_flag) {
        this.func_acl_flag = func_acl_flag;
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_session_flag
     *
     * @return the value of sy_func.func_session_flag
     *
     * @mbggenerated
     */
    public Integer getFunc_session_flag() {
        return func_session_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_session_flag
     *
     * @param func_session_flag the value for sy_func.func_session_flag
     *
     * @mbggenerated
     */
    public void setFunc_session_flag(Integer func_session_flag) {
        this.func_session_flag = func_session_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_readonly
     *
     * @return the value of sy_func.func_readonly
     *
     * @mbggenerated
     */
    public Integer getFunc_readonly() {
        return func_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_readonly
     *
     * @param func_readonly the value for sy_func.func_readonly
     *
     * @mbggenerated
     */
    public void setFunc_readonly(Integer func_readonly) {
        this.func_readonly = func_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_readonly_exp
     *
     * @return the value of sy_func.func_readonly_exp
     *
     * @mbggenerated
     */
    public String getFunc_readonly_exp() {
        return func_readonly_exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_readonly_exp
     *
     * @param func_readonly_exp the value for sy_func.func_readonly_exp
     *
     * @mbggenerated
     */
    public void setFunc_readonly_exp(String func_readonly_exp) {
        this.func_readonly_exp = func_readonly_exp == null ? null : func_readonly_exp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_delete_exp
     *
     * @return the value of sy_func.func_delete_exp
     *
     * @mbggenerated
     */
    public String getFunc_delete_exp() {
        return func_delete_exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_delete_exp
     *
     * @param func_delete_exp the value for sy_func.func_delete_exp
     *
     * @mbggenerated
     */
    public void setFunc_delete_exp(String func_delete_exp) {
        this.func_delete_exp = func_delete_exp == null ? null : func_delete_exp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_where
     *
     * @return the value of sy_func.func_where
     *
     * @mbggenerated
     */
    public String getFunc_where() {
        return func_where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_where
     *
     * @param func_where the value for sy_func.func_where
     *
     * @mbggenerated
     */
    public void setFunc_where(String func_where) {
        this.func_where = func_where == null ? null : func_where.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_info
     *
     * @return the value of sy_func.func_info
     *
     * @mbggenerated
     */
    public String getFunc_info() {
        return func_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_info
     *
     * @param func_info the value for sy_func.func_info
     *
     * @mbggenerated
     */
    public void setFunc_info(String func_info) {
        this.func_info = func_info == null ? null : func_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_param
     *
     * @return the value of sy_func.func_param
     *
     * @mbggenerated
     */
    public String getFunc_param() {
        return func_param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_param
     *
     * @param func_param the value for sy_func.func_param
     *
     * @mbggenerated
     */
    public void setFunc_param(String func_param) {
        this.func_param = func_param == null ? null : func_param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_comment
     *
     * @return the value of sy_func.func_comment
     *
     * @mbggenerated
     */
    public String getFunc_comment() {
        return func_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_comment
     *
     * @param func_comment the value for sy_func.func_comment
     *
     * @mbggenerated
     */
    public void setFunc_comment(String func_comment) {
        this.func_comment = func_comment == null ? null : func_comment.trim();
    }

	public Integer getFunc_action_flag() {
		return func_action_flag;
	}

	public void setFunc_action_flag(Integer func_action_flag) {
		this.func_action_flag = func_action_flag;
	}

	public String getFunc_wf_link_proctype() {
		return func_wf_link_proctype;
	}

	public void setFunc_wf_link_proctype(String func_wf_link_proctype) {
		this.func_wf_link_proctype = func_wf_link_proctype;
	}

	public String getFunc_wf_finish_allow() {
		return func_wf_finish_allow;
	}

	public void setFunc_wf_finish_allow(String func_wf_finish_allow) {
		this.func_wf_finish_allow = func_wf_finish_allow;
	}

	public String getFunc_wf_task_push() {
		return func_wf_task_push;
	}

	public void setFunc_wf_task_push(String func_wf_task_push) {
		this.func_wf_task_push = func_wf_task_push;
	}

	public String getFunc_wf_remind_push() {
		return func_wf_remind_push;
	}

	public void setFunc_wf_remind_push(String func_wf_remind_push) {
		this.func_wf_remind_push = func_wf_remind_push;
	}

	public String getFunc_pc_code() {
		return func_pc_code;
	}

	public void setFunc_pc_code(String func_pc_code) {
		this.func_pc_code = func_pc_code;
	}

	public String getFunc_mobile_code() {
		return func_mobile_code;
	}

	public void setFunc_mobile_code(String func_mobile_code) {
		this.func_mobile_code = func_mobile_code;
	}

	public Integer getFunc_layout() {
		return func_layout;
	}

	public void setFunc_layout(Integer func_layout) {
		this.func_layout = func_layout;
	}

	public Integer getFunc_isinit() {
		return func_isinit;
	}

	public void setFunc_isinit(Integer func_isinit) {
		this.func_isinit = func_isinit;
	}

	public String getFunc_version() {
		return func_version;
	}

	public void setFunc_version(String func_version) {
		this.func_version = func_version;
	}

}