package com.hayden.hap.common.entity.func;

/**
 * 
 * @author zhangfeng
 * @date 2018年1月29日
 */
public class FuncPCVO extends FuncVO {

	private static final long serialVersionUID = 1L;

	public FuncPCVO() {
		super("SY_FUNC");
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_short_code
     *
     * @mbggenerated
     */
    private String func_short_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.func_opensearch
     *
     * @mbggenerated
     */
    private Integer func_opensearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func.list_include_page
     *
     * @mbggenerated
     */
    private String list_include_page;

    
    /**
     * 全息查询字段
     */
    private String func_tree;
    
    /**
     * 客户端类型
     */
    private String func_clienttype;
    
    /**
     * 产品包含js
     */
    private String func_product_js;
    
    /**
     * 项目包含js
     */
    private String func_project_js;   

    /**
     * 全息树默认选中节点的值
     */
    private String func_tree_default;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_short_code
     *
     * @return the value of sy_func.func_short_code
     *
     * @mbggenerated
     */
    public String getFunc_short_code() {
        return func_short_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_short_code
     *
     * @param func_short_code the value for sy_func.func_short_code
     *
     * @mbggenerated
     */
    public void setFunc_short_code(String func_short_code) {
        this.func_short_code = func_short_code == null ? null : func_short_code.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.func_opensearch
     *
     * @return the value of sy_func.func_opensearch
     *
     * @mbggenerated
     */
    public Integer getFunc_opensearch() {
        return func_opensearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.func_opensearch
     *
     * @param func_opensearch the value for sy_func.func_opensearch
     *
     * @mbggenerated
     */
    public void setFunc_opensearch(Integer func_opensearch) {
        this.func_opensearch = func_opensearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func.list_include_page
     *
     * @return the value of sy_func.list_include_page
     *
     * @mbggenerated
     */
    public String getList_include_page() {
        return list_include_page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func.list_include_page
     *
     * @param list_include_page the value for sy_func.list_include_page
     *
     * @mbggenerated
     */
    public void setList_include_page(String list_include_page) {
        this.list_include_page = list_include_page == null ? null : list_include_page.trim();
    }

   

   

	public String getFunc_tree() {
		return func_tree;
	}

	public void setFunc_tree(String func_tree) {
		this.func_tree = func_tree;
	}

	public String getFunc_clienttype() {
		return func_clienttype;
	}

	public void setFunc_clienttype(String func_clienttype) {
		this.func_clienttype = func_clienttype;
	}
	

	public String getFunc_product_js() {
		return func_product_js;
	}

	public void setFunc_product_js(String func_product_js) {
		this.func_product_js = func_product_js;
	}

	public String getFunc_project_js() {
		return func_project_js;
	}

	public void setFunc_project_js(String func_project_js) {
		this.func_project_js = func_project_js;
	}

	public String getFunc_tree_default() {
		return func_tree_default;
	}

	public void setFunc_tree_default(String func_tree_default) {
		this.func_tree_default = func_tree_default;
	}
	
	
}
