package com.hayden.hap.common.entity.meun;

import com.hayden.hap.dbop.entity.BaseVO;

public class MenuVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menuid
	 *
	 * @mbggenerated
	 */
	private Long menuid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.tenantid
	 *
	 * @mbggenerated
	 */
	private Long tenantid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menucode
	 *
	 * @mbggenerated
	 */
	private String menucode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menuname
	 *
	 * @mbggenerated
	 */
	private String menuname;
	
	private String menuicon;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menuorder
	 *
	 * @mbggenerated
	 */
	private Integer menuorder;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.isleaf
	 *
	 * @mbggenerated
	 */
	private Integer isleaf;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.isenable
	 *
	 * @mbggenerated
	 */
	private Integer isenable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menutype
	 *
	 * @mbggenerated
	 */
	private String menutype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.func_code
	 *
	 * @mbggenerated
	 */
	private String func_code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.menuinfo
	 *
	 * @mbggenerated
	 */
	private String menuinfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_menu.parentid
	 *
	 * @mbggenerated
	 */
	private Long parentid;

	/**
	 * 是否已购买
	 */
	private Integer is_buy;
	
	/**
	 * 客户端类型
	 */
	private String menuclienttype;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sy_menu
	 *
	 * @mbggenerated
	 */
	public MenuVO() {
		super("SY_MENU");
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menuid
	 *
	 * @return the value of sy_menu.menuid
	 *
	 * @mbggenerated
	 */
	public Long getMenuid() {
		return menuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menuid
	 *
	 * @param menuid
	 *            the value for sy_menu.menuid
	 *
	 * @mbggenerated
	 */
	public void setMenuid(Long menuid) {
		this.menuid = menuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.tenantid
	 *
	 * @return the value of sy_menu.tenantid
	 *
	 * @mbggenerated
	 */
	public Long getTenantid() {
		return tenantid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.tenantid
	 *
	 * @param tenantid
	 *            the value for sy_menu.tenantid
	 *
	 * @mbggenerated
	 */
	public void setTenantid(Long tenantid) {
		this.tenantid = tenantid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menucode
	 *
	 * @return the value of sy_menu.menucode
	 *
	 * @mbggenerated
	 */
	public String getMenucode() {
		return menucode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menucode
	 *
	 * @param menucode
	 *            the value for sy_menu.menucode
	 *
	 * @mbggenerated
	 */
	public void setMenucode(String menucode) {
		this.menucode = menucode == null ? null : menucode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menuname
	 *
	 * @return the value of sy_menu.menuname
	 *
	 * @mbggenerated
	 */
	public String getMenuname() {
		return menuname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menuname
	 *
	 * @param menuname
	 *            the value for sy_menu.menuname
	 *
	 * @mbggenerated
	 */
	public void setMenuname(String menuname) {
		this.menuname = menuname == null ? null : menuname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menuorder
	 *
	 * @return the value of sy_menu.menuorder
	 *
	 * @mbggenerated
	 */
	public Integer getMenuorder() {
		return menuorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menuorder
	 *
	 * @param menuorder
	 *            the value for sy_menu.menuorder
	 *
	 * @mbggenerated
	 */
	public void setMenuorder(Integer menuorder) {
		this.menuorder = menuorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.isleaf
	 *
	 * @return the value of sy_menu.isleaf
	 *
	 * @mbggenerated
	 */
	public Integer getIsleaf() {
		return isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.isleaf
	 *
	 * @param isleaf
	 *            the value for sy_menu.isleaf
	 *
	 * @mbggenerated
	 */
	public void setIsleaf(Integer isleaf) {
		this.isleaf = isleaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.isenable
	 *
	 * @return the value of sy_menu.isenable
	 *
	 * @mbggenerated
	 */
	public Integer getIsenable() {
		return isenable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.isenable
	 *
	 * @param isenable
	 *            the value for sy_menu.isenable
	 *
	 * @mbggenerated
	 */
	public void setIsenable(Integer isenable) {
		this.isenable = isenable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menutype
	 *
	 * @return the value of sy_menu.menutype
	 *
	 * @mbggenerated
	 */
	public String getMenutype() {
		return menutype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menutype
	 *
	 * @param menutype
	 *            the value for sy_menu.menutype
	 *
	 * @mbggenerated
	 */
	public void setMenutype(String menutype) {
		this.menutype = menutype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.func_code
	 *
	 * @return the value of sy_menu.func_code
	 *
	 * @mbggenerated
	 */
	public String getFunc_code() {
		return func_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.func_code
	 *
	 * @param func_code
	 *            the value for sy_menu.func_code
	 *
	 * @mbggenerated
	 */
	public void setFunc_code(String func_code) {
		this.func_code = func_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.menuinfo
	 *
	 * @return the value of sy_menu.menuinfo
	 *
	 * @mbggenerated
	 */
	public String getMenuinfo() {
		return menuinfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.menuinfo
	 *
	 * @param menuinfo
	 *            the value for sy_menu.menuinfo
	 *
	 * @mbggenerated
	 */
	public void setMenuinfo(String menuinfo) {
		this.menuinfo = menuinfo == null ? null : menuinfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sy_menu.parentid
	 *
	 * @return the value of sy_menu.parentid
	 *
	 * @mbggenerated
	 */
	public Long getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sy_menu.parentid
	 *
	 * @param parentid
	 *            the value for sy_menu.parentid
	 *
	 * @mbggenerated
	 */
	public void setParentid(Long parentid) {
		this.parentid = parentid;
	}

	public Integer getIs_buy() {
		return is_buy;
	}

	public void setIs_buy(Integer is_buy) {
		this.is_buy = is_buy;
	}

	public String getMenuclienttype() {
		return menuclienttype;
	}

	public void setMenuclienttype(String menuclienttype) {
		this.menuclienttype = menuclienttype;
	}

	public String getMenuicon() {
		return menuicon;
	}

	public void setMenuicon(String menuicon) {
		this.menuicon = menuicon == null ? null : menuicon.trim();
	}

}