package com.hayden.hap.common.entity.meun;

import com.hayden.hap.dbop.entity.BaseVO;
import lombok.Data;

import java.util.List;

@Data
public class MenuMVO extends BaseVO {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menuid
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Long menuid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menucode
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String menucode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menuname
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String menuname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.uniquecode
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String uniquecode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menuorder
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Integer menuorder;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.isleaf
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Integer isleaf;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.isenable
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Integer isenable;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menutype
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String menutype;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.func_code
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String func_code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.menuinfo
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private String menuinfo;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.parentid
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Long parentid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.product_flag
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Integer product_flag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sy_menu_mobile.is_buy
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	private Integer is_buy;
	
	private List<MenuMVO> children;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sy_menu_mobile
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public MenuMVO() {
		super("sy_menu_mobile");
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.menucode
	 *
	 * @param menucode
	 *            the value for sy_menu_mobile.menucode
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setMenucode(String menucode) {
		this.menucode = menucode == null ? null : menucode.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.menuname
	 *
	 * @param menuname
	 *            the value for sy_menu_mobile.menuname
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setMenuname(String menuname) {
		this.menuname = menuname == null ? null : menuname.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.uniquecode
	 *
	 * @param uniquecode
	 *            the value for sy_menu_mobile.uniquecode
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setUniquecode(String uniquecode) {
		this.uniquecode = uniquecode == null ? null : uniquecode.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.menutype
	 *
	 * @param menutype
	 *            the value for sy_menu_mobile.menutype
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setMenutype(String menutype) {
		this.menutype = menutype == null ? null : menutype.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.func_code
	 *
	 * @param func_code
	 *            the value for sy_menu_mobile.func_code
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setFunc_code(String func_code) {
		this.func_code = func_code == null ? null : func_code.trim();
	}

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sy_menu_mobile.menuinfo
	 *
	 * @param menuinfo
	 *            the value for sy_menu_mobile.menuinfo
	 *
	 * @mbggenerated Thu May 10 19:42:02 CST 2018
	 */
	public void setMenuinfo(String menuinfo) {
		this.menuinfo = menuinfo == null ? null : menuinfo.trim();
	}

}