package com.hayden.hap.common.entity.dict;

import com.hayden.hap.dbop.entity.BaseVO;

import java.util.Date;

public class DictVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dictid
     *
     * @mbggenerated
     */
    private Long dictid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.modulecode
     *
     * @mbggenerated
     */
    private String modulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_code
     *
     * @mbggenerated
     */
    private String dict_code;
    
    private int dict_data_flag;
    

    public int getDict_data_flag() {
		return dict_data_flag;
	}

	public void setDict_data_flag(int dict_data_flag) {
		this.dict_data_flag = dict_data_flag;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_name
     *
     * @mbggenerated
     */
    private String dict_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_type
     *
     * @mbggenerated
     */
    private String dict_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_t_table
     *
     * @mbggenerated
     */
    private String dict_t_table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_t_type
     *
     * @mbggenerated
     */
    private String dict_t_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_code
     *
     * @mbggenerated
     */
    private String dict_f_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_layer
     *
     * @mbggenerated
     */
    private String dict_f_layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_name
     *
     * @mbggenerated
     */
    private String dict_f_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_isleaf
     *
     * @mbggenerated
     */
    private String dict_f_isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_order
     *
     * @mbggenerated
     */
    private String dict_f_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_isenable
     *
     * @mbggenerated
     */
    private String dict_f_isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_f_parent
     *
     * @mbggenerated
     */
    private String dict_f_parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_isenable
     *
     * @mbggenerated
     */
    private Integer dict_isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_showlayer
     *
     * @mbggenerated
     */
    private Integer dict_showlayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_isasync
     *
     * @mbggenerated
     */
    private Integer dict_isasync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.created_by
     *
     * @mbggenerated
     */
    private Long created_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.created_dt
     *
     * @mbggenerated
     */
    private Date created_dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.updated_by
     *
     * @mbggenerated
     */
    private Long updated_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.updated_dt
     *
     * @mbggenerated
     */
    private Date updated_dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict.dict_ispush
     *
     * @mbggenerated
     */
    private Integer dict_ispush;

    /**
     * 过滤条件
     */
    private String dict_where;
    
    /**
     * 产品/项目标识
     */
    private Integer product_flag;
    
    /**
     * 字典版本号
     */
    private Long dict_version;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dict
     *
     * @mbggenerated
     */
    public DictVO() {
        super("SY_DICT");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dictid
     *
     * @return the value of sy_dict.dictid
     *
     * @mbggenerated
     */
    public Long getDictid() {
        return dictid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dictid
     *
     * @param dictid the value for sy_dict.dictid
     *
     * @mbggenerated
     */
    public void setDictid(Long dictid) {
        this.dictid = dictid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.tenantid
     *
     * @return the value of sy_dict.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.tenantid
     *
     * @param tenantid the value for sy_dict.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.modulecode
     *
     * @return the value of sy_dict.modulecode
     *
     * @mbggenerated
     */
    public String getModulecode() {
        return modulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.modulecode
     *
     * @param modulecode the value for sy_dict.modulecode
     *
     * @mbggenerated
     */
    public void setModulecode(String modulecode) {
        this.modulecode = modulecode == null ? null : modulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_code
     *
     * @return the value of sy_dict.dict_code
     *
     * @mbggenerated
     */
    public String getDict_code() {
        return dict_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_code
     *
     * @param dict_code the value for sy_dict.dict_code
     *
     * @mbggenerated
     */
    public void setDict_code(String dict_code) {
        this.dict_code = dict_code == null ? null : dict_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_name
     *
     * @return the value of sy_dict.dict_name
     *
     * @mbggenerated
     */
    public String getDict_name() {
        return dict_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_name
     *
     * @param dict_name the value for sy_dict.dict_name
     *
     * @mbggenerated
     */
    public void setDict_name(String dict_name) {
        this.dict_name = dict_name == null ? null : dict_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_type
     *
     * @return the value of sy_dict.dict_type
     *
     * @mbggenerated
     */
    public String getDict_type() {
        return dict_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_type
     *
     * @param dict_type the value for sy_dict.dict_type
     *
     * @mbggenerated
     */
    public void setDict_type(String dict_type) {
        this.dict_type = dict_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_t_table
     *
     * @return the value of sy_dict.dict_t_table
     *
     * @mbggenerated
     */
    public String getDict_t_table() {
        return dict_t_table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_t_table
     *
     * @param dict_t_table the value for sy_dict.dict_t_table
     *
     * @mbggenerated
     */
    public void setDict_t_table(String dict_t_table) {
        this.dict_t_table = dict_t_table == null ? null : dict_t_table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_t_type
     *
     * @return the value of sy_dict.dict_t_type
     *
     * @mbggenerated
     */
    public String getDict_t_type() {
        return dict_t_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_t_type
     *
     * @param dict_t_type the value for sy_dict.dict_t_type
     *
     * @mbggenerated
     */
    public void setDict_t_type(String dict_t_type) {
        this.dict_t_type = dict_t_type == null ? null : dict_t_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_code
     *
     * @return the value of sy_dict.dict_f_code
     *
     * @mbggenerated
     */
    public String getDict_f_code() {
        return dict_f_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_code
     *
     * @param dict_f_code the value for sy_dict.dict_f_code
     *
     * @mbggenerated
     */
    public void setDict_f_code(String dict_f_code) {
        this.dict_f_code = dict_f_code == null ? null : dict_f_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_layer
     *
     * @return the value of sy_dict.dict_f_layer
     *
     * @mbggenerated
     */
    public String getDict_f_layer() {
        return dict_f_layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_layer
     *
     * @param dict_f_layer the value for sy_dict.dict_f_layer
     *
     * @mbggenerated
     */
    public void setDict_f_layer(String dict_f_layer) {
        this.dict_f_layer = dict_f_layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_name
     *
     * @return the value of sy_dict.dict_f_name
     *
     * @mbggenerated
     */
    public String getDict_f_name() {
        return dict_f_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_name
     *
     * @param dict_f_name the value for sy_dict.dict_f_name
     *
     * @mbggenerated
     */
    public void setDict_f_name(String dict_f_name) {
        this.dict_f_name = dict_f_name == null ? null : dict_f_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_isleaf
     *
     * @return the value of sy_dict.dict_f_isleaf
     *
     * @mbggenerated
     */
    public String getDict_f_isleaf() {
        return dict_f_isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_isleaf
     *
     * @param dict_f_isleaf the value for sy_dict.dict_f_isleaf
     *
     * @mbggenerated
     */
    public void setDict_f_isleaf(String dict_f_isleaf) {
        this.dict_f_isleaf = dict_f_isleaf == null ? null : dict_f_isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_order
     *
     * @return the value of sy_dict.dict_f_order
     *
     * @mbggenerated
     */
    public String getDict_f_order() {
        return dict_f_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_order
     *
     * @param dict_f_order the value for sy_dict.dict_f_order
     *
     * @mbggenerated
     */
    public void setDict_f_order(String dict_f_order) {
        this.dict_f_order = dict_f_order == null ? null : dict_f_order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_isenable
     *
     * @return the value of sy_dict.dict_f_isenable
     *
     * @mbggenerated
     */
    public String getDict_f_isenable() {
        return dict_f_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_isenable
     *
     * @param dict_f_isenable the value for sy_dict.dict_f_isenable
     *
     * @mbggenerated
     */
    public void setDict_f_isenable(String dict_f_isenable) {
        this.dict_f_isenable = dict_f_isenable == null ? null : dict_f_isenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_f_parent
     *
     * @return the value of sy_dict.dict_f_parent
     *
     * @mbggenerated
     */
    public String getDict_f_parent() {
        return dict_f_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_f_parent
     *
     * @param dict_f_parent the value for sy_dict.dict_f_parent
     *
     * @mbggenerated
     */
    public void setDict_f_parent(String dict_f_parent) {
        this.dict_f_parent = dict_f_parent == null ? null : dict_f_parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_isenable
     *
     * @return the value of sy_dict.dict_isenable
     *
     * @mbggenerated
     */
    public Integer getDict_isenable() {
        return dict_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_isenable
     *
     * @param dict_isenable the value for sy_dict.dict_isenable
     *
     * @mbggenerated
     */
    public void setDict_isenable(Integer dict_isenable) {
        this.dict_isenable = dict_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_showlayer
     *
     * @return the value of sy_dict.dict_showlayer
     *
     * @mbggenerated
     */
    public Integer getDict_showlayer() {
        return dict_showlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_showlayer
     *
     * @param dict_showlayer the value for sy_dict.dict_showlayer
     *
     * @mbggenerated
     */
    public void setDict_showlayer(Integer dict_showlayer) {
        this.dict_showlayer = dict_showlayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_isasync
     *
     * @return the value of sy_dict.dict_isasync
     *
     * @mbggenerated
     */
    public Integer getDict_isasync() {
        return dict_isasync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_isasync
     *
     * @param dict_isasync the value for sy_dict.dict_isasync
     *
     * @mbggenerated
     */
    public void setDict_isasync(Integer dict_isasync) {
        this.dict_isasync = dict_isasync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.created_by
     *
     * @return the value of sy_dict.created_by
     *
     * @mbggenerated
     */
    public Long getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.created_by
     *
     * @param created_by the value for sy_dict.created_by
     *
     * @mbggenerated
     */
    public void setCreated_by(Long created_by) {
        this.created_by = created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.created_dt
     *
     * @return the value of sy_dict.created_dt
     *
     * @mbggenerated
     */
    public Date getCreated_dt() {
        return created_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.created_dt
     *
     * @param created_dt the value for sy_dict.created_dt
     *
     * @mbggenerated
     */
    public void setCreated_dt(Date created_dt) {
        this.created_dt = created_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.updated_by
     *
     * @return the value of sy_dict.updated_by
     *
     * @mbggenerated
     */
    public Long getUpdated_by() {
        return updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.updated_by
     *
     * @param updated_by the value for sy_dict.updated_by
     *
     * @mbggenerated
     */
    public void setUpdated_by(Long updated_by) {
        this.updated_by = updated_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.updated_dt
     *
     * @return the value of sy_dict.updated_dt
     *
     * @mbggenerated
     */
    public Date getUpdated_dt() {
        return updated_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.updated_dt
     *
     * @param updated_dt the value for sy_dict.updated_dt
     *
     * @mbggenerated
     */
    public void setUpdated_dt(Date updated_dt) {
        this.updated_dt = updated_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict.dict_ispush
     *
     * @return the value of sy_dict.dict_ispush
     *
     * @mbggenerated
     */
    public Integer getDict_ispush() {
        return dict_ispush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict.dict_ispush
     *
     * @param dict_ispush the value for sy_dict.dict_ispush
     *
     * @mbggenerated
     */
    public void setDict_ispush(Integer dict_ispush) {
        this.dict_ispush = dict_ispush;
    }

	public String getDict_where() {
		return dict_where;
	}

	public void setDict_where(String dict_where) {
		this.dict_where = dict_where;
	}

	public Integer getProduct_flag() {
		return product_flag;
	}

	public void setProduct_flag(Integer product_flag) {
		this.product_flag = product_flag;
	}

	public Long getDict_version() {
		return dict_version;
	}

	public void setDict_version(Long dict_version) {
		this.dict_version = dict_version;
	}
}