package com.hayden.hap.common.entity.dict;

import com.hayden.hap.dbop.entity.BaseVO;

import java.util.List;

public class DictDataVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dictdataid
     *
     * @mbggenerated
     */
    private Long dictdataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dictid
     *
     * @mbggenerated
     */
    private Long dictid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_code
     *
     * @mbggenerated
     */
    private String dict_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_code
     *
     * @mbggenerated
     */
    private String dict_data_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_name
     *
     * @mbggenerated
     */
    private String dict_data_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_layer
     *
     * @mbggenerated
     */
    private Integer dict_data_layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_parent
     *
     * @mbggenerated
     */
    private Long dict_data_parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_isleaf
     *
     * @mbggenerated
     */
    private Integer dict_data_isleaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_dict_data.dict_data_order
     *
     * @mbggenerated
     */
    private String dict_data_order;
    
    private Integer dict_data_isenable;
    
    private List<DictDataVO> children;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_dict_data
     *
     * @mbggenerated
     */
    public DictDataVO() {
        super("SY_DICT_DATA");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dictdataid
     *
     * @return the value of sy_dict_data.dictdataid
     *
     * @mbggenerated
     */
    public Long getDictdataid() {
        return dictdataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dictdataid
     *
     * @param dictdataid the value for sy_dict_data.dictdataid
     *
     * @mbggenerated
     */
    public void setDictdataid(Long dictdataid) {
        this.dictdataid = dictdataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dictid
     *
     * @return the value of sy_dict_data.dictid
     *
     * @mbggenerated
     */
    public Long getDictid() {
        return dictid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dictid
     *
     * @param dictid the value for sy_dict_data.dictid
     *
     * @mbggenerated
     */
    public void setDictid(Long dictid) {
        this.dictid = dictid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.tenantid
     *
     * @return the value of sy_dict_data.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.tenantid
     *
     * @param tenantid the value for sy_dict_data.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_code
     *
     * @return the value of sy_dict_data.dict_code
     *
     * @mbggenerated
     */
    public String getDict_code() {
        return dict_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_code
     *
     * @param dict_code the value for sy_dict_data.dict_code
     *
     * @mbggenerated
     */
    public void setDict_code(String dict_code) {
        this.dict_code = dict_code == null ? null : dict_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_code
     *
     * @return the value of sy_dict_data.dict_data_code
     *
     * @mbggenerated
     */
    public String getDict_data_code() {
        return dict_data_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_code
     *
     * @param dict_data_code the value for sy_dict_data.dict_data_code
     *
     * @mbggenerated
     */
    public void setDict_data_code(String dict_data_code) {
        this.dict_data_code = dict_data_code == null ? null : dict_data_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_name
     *
     * @return the value of sy_dict_data.dict_data_name
     *
     * @mbggenerated
     */
    public String getDict_data_name() {
        return dict_data_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_name
     *
     * @param dict_data_name the value for sy_dict_data.dict_data_name
     *
     * @mbggenerated
     */
    public void setDict_data_name(String dict_data_name) {
        this.dict_data_name = dict_data_name == null ? null : dict_data_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_layer
     *
     * @return the value of sy_dict_data.dict_data_layer
     *
     * @mbggenerated
     */
    public Integer getDict_data_layer() {
        return dict_data_layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_layer
     *
     * @param dict_data_layer the value for sy_dict_data.dict_data_layer
     *
     * @mbggenerated
     */
    public void setDict_data_layer(Integer dict_data_layer) {
        this.dict_data_layer = dict_data_layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_parent
     *
     * @return the value of sy_dict_data.dict_data_parent
     *
     * @mbggenerated
     */
    public Long getDict_data_parent() {
        return dict_data_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_parent
     *
     * @param dict_data_parent the value for sy_dict_data.dict_data_parent
     *
     * @mbggenerated
     */
    public void setDict_data_parent(Long dict_data_parent) {
        this.dict_data_parent = dict_data_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_isleaf
     *
     * @return the value of sy_dict_data.dict_data_isleaf
     *
     * @mbggenerated
     */
    public Integer getDict_data_isleaf() {
        return dict_data_isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_isleaf
     *
     * @param dict_data_isleaf the value for sy_dict_data.dict_data_isleaf
     *
     * @mbggenerated
     */
    public void setDict_data_isleaf(Integer dict_data_isleaf) {
        this.dict_data_isleaf = dict_data_isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_dict_data.dict_data_order
     *
     * @return the value of sy_dict_data.dict_data_order
     *
     * @mbggenerated
     */
    public String getDict_data_order() {
        return dict_data_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_dict_data.dict_data_order
     *
     * @param dict_data_order the value for sy_dict_data.dict_data_order
     *
     * @mbggenerated
     */
    public void setDict_data_order(String dict_data_order) {
        this.dict_data_order = dict_data_order;
    }

	public List<DictDataVO> getChildren() {
		return children;
	}

	public void setChildren(List<DictDataVO> children) {
		this.children = children;
	}

	public Integer getDict_data_isenable() {
		return dict_data_isenable;
	}

	public void setDict_data_isenable(Integer dict_data_isenable) {
		this.dict_data_isenable = dict_data_isenable;
	}
	
	  private String danger_level;

		public String getDanger_level() {
			return danger_level;
		}

		public void setDanger_level(String danger_level) {
			this.danger_level = danger_level;
		}
}