package com.hayden.hap.common.form.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class FormButtonMobileVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_id
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Long btn_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.formid
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Long formid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.form_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String form_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_name
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_order
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Integer btn_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.product_flag
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Integer product_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_show_control
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_show_control;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_type
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_isenable
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Integer btn_isenable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_inputconfig
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_inputconfig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_img
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_group
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_history
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private Integer btn_history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_param
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_button_mobile.btn_comment
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    private String btn_comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_form_button_mobile
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public FormButtonMobileVO() {
        super("sy_form_button_mobile");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_id
     *
     * @return the value of sy_form_button_mobile.btn_id
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Long getBtn_id() {
        return btn_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_id
     *
     * @param btn_id the value for sy_form_button_mobile.btn_id
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_id(Long btn_id) {
        this.btn_id = btn_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.formid
     *
     * @return the value of sy_form_button_mobile.formid
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Long getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.formid
     *
     * @param formid the value for sy_form_button_mobile.formid
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setFormid(Long formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.form_code
     *
     * @return the value of sy_form_button_mobile.form_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getForm_code() {
        return form_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.form_code
     *
     * @param form_code the value for sy_form_button_mobile.form_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setForm_code(String form_code) {
        this.form_code = form_code == null ? null : form_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_code
     *
     * @return the value of sy_form_button_mobile.btn_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_code() {
        return btn_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_code
     *
     * @param btn_code the value for sy_form_button_mobile.btn_code
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_code(String btn_code) {
        this.btn_code = btn_code == null ? null : btn_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_name
     *
     * @return the value of sy_form_button_mobile.btn_name
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_name() {
        return btn_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_name
     *
     * @param btn_name the value for sy_form_button_mobile.btn_name
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_name(String btn_name) {
        this.btn_name = btn_name == null ? null : btn_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_order
     *
     * @return the value of sy_form_button_mobile.btn_order
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Integer getBtn_order() {
        return btn_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_order
     *
     * @param btn_order the value for sy_form_button_mobile.btn_order
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_order(Integer btn_order) {
        this.btn_order = btn_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.product_flag
     *
     * @return the value of sy_form_button_mobile.product_flag
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.product_flag
     *
     * @param product_flag the value for sy_form_button_mobile.product_flag
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_show_control
     *
     * @return the value of sy_form_button_mobile.btn_show_control
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_show_control() {
        return btn_show_control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_show_control
     *
     * @param btn_show_control the value for sy_form_button_mobile.btn_show_control
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_show_control(String btn_show_control) {
        this.btn_show_control = btn_show_control == null ? null : btn_show_control.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_type
     *
     * @return the value of sy_form_button_mobile.btn_type
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_type() {
        return btn_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_type
     *
     * @param btn_type the value for sy_form_button_mobile.btn_type
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_type(String btn_type) {
        this.btn_type = btn_type == null ? null : btn_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_isenable
     *
     * @return the value of sy_form_button_mobile.btn_isenable
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Integer getBtn_isenable() {
        return btn_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_isenable
     *
     * @param btn_isenable the value for sy_form_button_mobile.btn_isenable
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_isenable(Integer btn_isenable) {
        this.btn_isenable = btn_isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_inputconfig
     *
     * @return the value of sy_form_button_mobile.btn_inputconfig
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_inputconfig() {
        return btn_inputconfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_inputconfig
     *
     * @param btn_inputconfig the value for sy_form_button_mobile.btn_inputconfig
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_inputconfig(String btn_inputconfig) {
        this.btn_inputconfig = btn_inputconfig == null ? null : btn_inputconfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_img
     *
     * @return the value of sy_form_button_mobile.btn_img
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_img() {
        return btn_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_img
     *
     * @param btn_img the value for sy_form_button_mobile.btn_img
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_img(String btn_img) {
        this.btn_img = btn_img == null ? null : btn_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_group
     *
     * @return the value of sy_form_button_mobile.btn_group
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_group() {
        return btn_group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_group
     *
     * @param btn_group the value for sy_form_button_mobile.btn_group
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_group(String btn_group) {
        this.btn_group = btn_group == null ? null : btn_group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_history
     *
     * @return the value of sy_form_button_mobile.btn_history
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public Integer getBtn_history() {
        return btn_history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_history
     *
     * @param btn_history the value for sy_form_button_mobile.btn_history
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_history(Integer btn_history) {
        this.btn_history = btn_history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_param
     *
     * @return the value of sy_form_button_mobile.btn_param
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_param() {
        return btn_param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_param
     *
     * @param btn_param the value for sy_form_button_mobile.btn_param
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_param(String btn_param) {
        this.btn_param = btn_param == null ? null : btn_param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_button_mobile.btn_comment
     *
     * @return the value of sy_form_button_mobile.btn_comment
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public String getBtn_comment() {
        return btn_comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_button_mobile.btn_comment
     *
     * @param btn_comment the value for sy_form_button_mobile.btn_comment
     *
     * @mbggenerated Wed May 09 11:20:16 CST 2018
     */
    public void setBtn_comment(String btn_comment) {
        this.btn_comment = btn_comment == null ? null : btn_comment.trim();
    }
}