package com.hayden.hap.common.form.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class FormConditionVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.id
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.condition_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private String condition_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.condition_name
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private String condition_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.form_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private String form_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.order
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private Integer condition_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_form_condition.isenable
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    private Integer isenable;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_form_condition
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public FormConditionVO() {
        super("sy_form_condition");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.id
     *
     * @return the value of sy_form_condition.id
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.id
     *
     * @param id the value for sy_form_condition.id
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.condition_code
     *
     * @return the value of sy_form_condition.condition_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public String getCondition_code() {
        return condition_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.condition_code
     *
     * @param condition_code the value for sy_form_condition.condition_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setCondition_code(String condition_code) {
        this.condition_code = condition_code == null ? null : condition_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.condition_name
     *
     * @return the value of sy_form_condition.condition_name
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public String getCondition_name() {
        return condition_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.condition_name
     *
     * @param condition_name the value for sy_form_condition.condition_name
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setCondition_name(String condition_name) {
        this.condition_name = condition_name == null ? null : condition_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.form_code
     *
     * @return the value of sy_form_condition.form_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public String getForm_code() {
        return form_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.form_code
     *
     * @param form_code the value for sy_form_condition.form_code
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setForm_code(String form_code) {
        this.form_code = form_code == null ? null : form_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.order
     *
     * @return the value of sy_form_condition.order
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public Integer getCondition_order() {
        return condition_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.order
     *
     * @param order the value for sy_form_condition.order
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setCondition_order(Integer condition_order) {
        this.condition_order = condition_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_form_condition.isenable
     *
     * @return the value of sy_form_condition.isenable
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public Integer getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_form_condition.isenable
     *
     * @param isenable the value for sy_form_condition.isenable
     *
     * @mbggenerated Mon Jun 07 11:33:20 CST 2021
     */
    public void setIsenable(Integer isenable) {
        this.isenable = isenable;
    }
}