package com.hayden.hap.dbop.db.tableDef.entity;


import com.hayden.hap.dbop.entity.BaseVO;
import org.apache.commons.lang3.StringUtils;

public class TableColumnVO extends BaseVO {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.tablecolumnid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Long tablecolumnid;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.table_code
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String table_code;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.coltype
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String coltype;
   /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column _table_column_v_o.coltype
   *
   * @mbggenerated Thu Dec 10 15:36:43 CST 2015
   */
  private String ora_coltype;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.collen
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer collen;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.colscale
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer colscale;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.colname
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String colname;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.coldesc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String coldesc;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.ispk
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer ispk;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.coldefault
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String coldefault;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.isnotnull
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer isnotnull;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.isautoinc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer isautoinc;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.gencode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String gencode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.colorder
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Integer colorder;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.colcode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private String colcode;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column _table_column_v_o.tabledefid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   private Long tabledefid;

   /**
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table _table_column_v_o
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public TableColumnVO() {
       super("SY_TABLE_COLUMN");
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.tablecolumnid
    *
    * @return the value of _table_column_v_o.tablecolumnid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Long getTablecolumnid() {
       return tablecolumnid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.tablecolumnid
    *
    * @param tablecolumnid the value for _table_column_v_o.tablecolumnid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setTablecolumnid(Long tablecolumnid) {
       this.tablecolumnid = tablecolumnid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.table_code
    *
    * @return the value of _table_column_v_o.table_code
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getTable_code() {
       return table_code;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.table_code
    *
    * @param table_code the value for _table_column_v_o.table_code
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setTable_code(String table_code) {
       this.table_code = table_code == null ? null : table_code.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.coltype
    *
    * @return the value of _table_column_v_o.coltype
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getColtype() {
       return coltype;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.coltype
    *
    * @param coltype the value for _table_column_v_o.coltype
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColtype(String coltype) {
       this.coltype = coltype == null ? null : coltype.trim();
   }

   public String getOra_coltype() {
	   if(StringUtils.isEmpty(ora_coltype)&&StringUtils.isNotEmpty(coltype)){
		   ora_coltype = DataTypeUtil.getOracleColType(coltype);
	   }	   
		return ora_coltype;
	}
	
	public void setOra_coltype(String ora_coltype) {
		this.ora_coltype = ora_coltype;
	}

/**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.collen
    *
    * @return the value of _table_column_v_o.collen
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getCollen() {
       return collen;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.collen
    *
    * @param collen the value for _table_column_v_o.collen
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setCollen(Integer collen) {
       this.collen = collen;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.colscale
    *
    * @return the value of _table_column_v_o.colscale
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getColscale() {
       return colscale;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.colscale
    *
    * @param colscale the value for _table_column_v_o.colscale
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColscale(Integer colscale) {
       this.colscale = colscale;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.colname
    *
    * @return the value of _table_column_v_o.colname
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getColname() {
       return colname;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.colname
    *
    * @param colname the value for _table_column_v_o.colname
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColname(String colname) {
       this.colname = colname == null ? null : colname.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.coldesc
    *
    * @return the value of _table_column_v_o.coldesc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getColdesc() {
       return coldesc;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.coldesc
    *
    * @param coldesc the value for _table_column_v_o.coldesc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColdesc(String coldesc) {
       this.coldesc = coldesc == null ? null : coldesc.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.ispk
    *
    * @return the value of _table_column_v_o.ispk
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getIspk() {
       return ispk;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.ispk
    *
    * @param ispk the value for _table_column_v_o.ispk
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setIspk(Integer ispk) {
       this.ispk = ispk;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.coldefault
    *
    * @return the value of _table_column_v_o.coldefault
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getColdefault() {
       return coldefault;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.coldefault
    *
    * @param coldefault the value for _table_column_v_o.coldefault
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColdefault(String coldefault) {
       this.coldefault = coldefault == null ? null : coldefault.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.isnotnull
    *
    * @return the value of _table_column_v_o.isnotnull
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getIsnotnull() {
       return isnotnull;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.isnotnull
    *
    * @param isnotnull the value for _table_column_v_o.isnotnull
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setIsnotnull(Integer isnotnull) {
       this.isnotnull = isnotnull;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.isautoinc
    *
    * @return the value of _table_column_v_o.isautoinc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getIsautoinc() {
       return isautoinc;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.isautoinc
    *
    * @param isautoinc the value for _table_column_v_o.isautoinc
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setIsautoinc(Integer isautoinc) {
       this.isautoinc = isautoinc;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.gencode
    *
    * @return the value of _table_column_v_o.gencode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getGencode() {
       return gencode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.gencode
    *
    * @param gencode the value for _table_column_v_o.gencode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setGencode(String gencode) {
       this.gencode = gencode == null ? null : gencode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.colorder
    *
    * @return the value of _table_column_v_o.colorder
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Integer getColorder() {
       return colorder;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.colorder
    *
    * @param colorder the value for _table_column_v_o.colorder
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColorder(Integer colorder) {
       this.colorder = colorder;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.colcode
    *
    * @return the value of _table_column_v_o.colcode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public String getColcode() {
       return colcode;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.colcode
    *
    * @param colcode the value for _table_column_v_o.colcode
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setColcode(String colcode) {
       this.colcode = colcode == null ? null : colcode.trim();
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method returns the value of the database column _table_column_v_o.tabledefid
    *
    * @return the value of _table_column_v_o.tabledefid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public Long getTabledefid() {
       return tabledefid;
   }

   /**
    * This method was generated by MyBatis Generator.
    * This method sets the value of the database column _table_column_v_o.tabledefid
    *
    * @param tabledefid the value for _table_column_v_o.tabledefid
    *
    * @mbggenerated Thu Dec 10 15:36:43 CST 2015
    */
   public void setTabledefid(Long tabledefid) {
       this.tabledefid = tabledefid;
   }
}