package com.hayden.hap.dbop.db.tableDef.entity;

import com.hayden.hap.dbop.entity.BaseVO;

import java.util.List;

/** 
 * @ClassName: TableDefVO 
 * @Description: 
 * @author LUYANYING
 * @date 2015年4月14日 上午11:45:36 
 * @version V1.0   
 *  
 */
public class TableDefVO extends BaseVO {
   
	private List<TableColumnVO> columnList = null;
	
	private TableColumnVO pkColumnVO = null;	
	
	//当存在联合主键时需要记录所有涉及的字段
	private List<TableColumnVO> pkColumnVOList = null;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.tabledefid
     *
     * @mbggenerated
     */
    private Long tabledefid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.table_code
     *
     * @mbggenerated
     */
    private String table_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.modulecode
     *
     * @mbggenerated
     */
    private String modulecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.issqllog
     *
     * @mbggenerated
     */
    private Integer issqllog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.table_desc
     *
     * @mbggenerated
     */
    private String table_desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.ddlsql
     *
     * @mbggenerated
     */
    private String ddlsql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.classname
     *
     * @mbggenerated
     */
    private String classname;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.table_type
     *
     * @mbggenerated
     */
    private Integer table_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.table_name
     *
     * @mbggenerated
     */
    private String table_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_table_def.table_delwhere
     *
     * @mbggenerated
     */
    private String table_delwhere;
    
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sy_table_def.isenable
	 *
	 * @mbggenerated
	 */
	private Integer isenable;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_table_def
     *
     * @mbggenerated
     */
    public TableDefVO() {
        super("SY_TABLE_DEF");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.tabledefid
     *
     * @return the value of sy_table_def.tabledefid
     *
     * @mbggenerated
     */
    public Long getTabledefid() {
        return tabledefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.tabledefid
     *
     * @param tabledefid the value for sy_table_def.tabledefid
     *
     * @mbggenerated
     */
    public void setTabledefid(Long tabledefid) {
        this.tabledefid = tabledefid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.table_code
     *
     * @return the value of sy_table_def.table_code
     *
     * @mbggenerated
     */
    public String getTable_code() {
        return table_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.table_code
     *
     * @param table_code the value for sy_table_def.table_code
     *
     * @mbggenerated
     */
    public void setTable_code(String table_code) {
        this.table_code = table_code == null ? null : table_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.modulecode
     *
     * @return the value of sy_table_def.modulecode
     *
     * @mbggenerated
     */
    public String getModulecode() {
        return modulecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.modulecode
     *
     * @param modulecode the value for sy_table_def.modulecode
     *
     * @mbggenerated
     */
    public void setModulecode(String modulecode) {
        this.modulecode = modulecode == null ? null : modulecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.issqllog
     *
     * @return the value of sy_table_def.issqllog
     *
     * @mbggenerated
     */
    public Integer getIssqllog() {
        return issqllog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.issqllog
     *
     * @param issqllog the value for sy_table_def.issqllog
     *
     * @mbggenerated
     */
    public void setIssqllog(Integer issqllog) {
        this.issqllog = issqllog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.table_desc
     *
     * @return the value of sy_table_def.table_desc
     *
     * @mbggenerated
     */
    public String getTable_desc() {
        return table_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.table_desc
     *
     * @param table_desc the value for sy_table_def.table_desc
     *
     * @mbggenerated
     */
    public void setTable_desc(String table_desc) {
        this.table_desc = table_desc == null ? null : table_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.ddlsql
     *
     * @return the value of sy_table_def.ddlsql
     *
     * @mbggenerated
     */
    public String getDdlsql() {
        return ddlsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.ddlsql
     *
     * @param ddlsql the value for sy_table_def.ddlsql
     *
     * @mbggenerated
     */
    public void setDdlsql(String ddlsql) {
        this.ddlsql = ddlsql == null ? null : ddlsql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.classname
     *
     * @return the value of sy_table_def.classname
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.classname
     *
     * @param classname the value for sy_table_def.classname
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.table_type
     *
     * @return the value of sy_table_def.table_type
     *
     * @mbggenerated
     */
    public Integer getTable_type() {
        return table_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.table_type
     *
     * @param table_type the value for sy_table_def.table_type
     *
     * @mbggenerated
     */
    public void setTable_type(Integer table_type) {
        this.table_type = table_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.table_name
     *
     * @return the value of sy_table_def.table_name
     *
     * @mbggenerated
     */
    public String getTable_name() {
        return table_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.table_name
     *
     * @param table_name the value for sy_table_def.table_name
     *
     * @mbggenerated
     */
    public void setTable_name(String table_name) {
        this.table_name = table_name == null ? null : table_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_table_def.table_delwhere
     *
     * @return the value of sy_table_def.table_delwhere
     *
     * @mbggenerated
     */
    public String getTable_delwhere() {
        return table_delwhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_table_def.table_delwhere
     *
     * @param table_delwhere the value for sy_table_def.table_delwhere
     *
     * @mbggenerated
     */
    public void setTable_delwhere(String table_delwhere) {
        this.table_delwhere = table_delwhere == null ? null : table_delwhere.trim();
    }
    
	public List<TableColumnVO> getColumnList() {
		return columnList;
	}

	public void setColumnList(List<TableColumnVO> columnList) {
		this.columnList = columnList;
	}
	public TableColumnVO getPkColumnVO() {
		return pkColumnVO;
	}

	public void setPkColumnVO(TableColumnVO pkColumnVO) {
		this.pkColumnVO = pkColumnVO;
	}

	public List<TableColumnVO> getPkColumnVOList() {
		return pkColumnVOList;
	}

	public void setPkColumnVOList(List<TableColumnVO> pkColumnVOList) {
		this.pkColumnVOList = pkColumnVOList;
	}

	public Integer getIsenable() {
		return isenable;
	}

	public void setIsenable(Integer isenable) {
		this.isenable = isenable;
	}
}
