package com.hayden.hap.common.func.entity;

import com.hayden.hap.common.common.entity.BaseVO;

import java.util.List;

public class FuncLinkMVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Long link_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String main_func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String sub_func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_name
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String link_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_where
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String link_where;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_control
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private String link_control;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_del
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_update
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_update;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_readonly
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_readonly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_forward_card
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_forward_card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_order
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_enable
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer product_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link_mobile.link_is_lazeload
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    private Integer link_is_lazeload;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_func_link_mobile.show_children_num
    *
    * @mbggenerated Wed Jan 02 10:00:21 CST 2019
    */
   private Integer show_children_num;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_func_link_mobile.link_is_show_subcard
    *
    * @mbggenerated Wed Jan 02 10:00:21 CST 2019
    */
   private Integer link_is_show_subcard;
    
    /**
     * 关联字段
     */
    private List<FuncLinkItemMVO> linkItems;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column sy_func_link_mobile.sub_func_config
    *
    * @mbggenerated Wed Jun 26 17:40:44 CST 2019
    */
    private String sub_func_config;
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_func_link_mobile
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public FuncLinkMVO() {
        super("SY_FUNC_LINK_MOBILE");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_id
     *
     * @return the value of sy_func_link_mobile.link_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Long getLink_id() {
        return link_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_id
     *
     * @param link_id the value for sy_func_link_mobile.link_id
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_id(Long link_id) {
        this.link_id = link_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.main_func_code
     *
     * @return the value of sy_func_link_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getMain_func_code() {
        return main_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.main_func_code
     *
     * @param main_func_code the value for sy_func_link_mobile.main_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setMain_func_code(String main_func_code) {
        this.main_func_code = main_func_code == null ? null : main_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.sub_func_code
     *
     * @return the value of sy_func_link_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getSub_func_code() {
        return sub_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.sub_func_code
     *
     * @param sub_func_code the value for sy_func_link_mobile.sub_func_code
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setSub_func_code(String sub_func_code) {
        this.sub_func_code = sub_func_code == null ? null : sub_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_name
     *
     * @return the value of sy_func_link_mobile.link_name
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLink_name() {
        return link_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_name
     *
     * @param link_name the value for sy_func_link_mobile.link_name
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_name(String link_name) {
        this.link_name = link_name == null ? null : link_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_where
     *
     * @return the value of sy_func_link_mobile.link_where
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLink_where() {
        return link_where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_where
     *
     * @param link_where the value for sy_func_link_mobile.link_where
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_where(String link_where) {
        this.link_where = link_where == null ? null : link_where.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_control
     *
     * @return the value of sy_func_link_mobile.link_control
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public String getLink_control() {
        return link_control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_control
     *
     * @param link_control the value for sy_func_link_mobile.link_control
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_control(String link_control) {
        this.link_control = link_control == null ? null : link_control.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_del
     *
     * @return the value of sy_func_link_mobile.link_is_del
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_del() {
        return link_is_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_del
     *
     * @param link_is_del the value for sy_func_link_mobile.link_is_del
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_del(Integer link_is_del) {
        this.link_is_del = link_is_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_update
     *
     * @return the value of sy_func_link_mobile.link_is_update
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_update() {
        return link_is_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_update
     *
     * @param link_is_update the value for sy_func_link_mobile.link_is_update
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_update(Integer link_is_update) {
        this.link_is_update = link_is_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_readonly
     *
     * @return the value of sy_func_link_mobile.link_is_readonly
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_readonly() {
        return link_is_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_readonly
     *
     * @param link_is_readonly the value for sy_func_link_mobile.link_is_readonly
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_readonly(Integer link_is_readonly) {
        this.link_is_readonly = link_is_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_forward_card
     *
     * @return the value of sy_func_link_mobile.link_is_forward_card
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_forward_card() {
        return link_is_forward_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_forward_card
     *
     * @param link_is_forward_card the value for sy_func_link_mobile.link_is_forward_card
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_forward_card(Integer link_is_forward_card) {
        this.link_is_forward_card = link_is_forward_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_order
     *
     * @return the value of sy_func_link_mobile.link_order
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_order() {
        return link_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_order
     *
     * @param link_order the value for sy_func_link_mobile.link_order
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_order(Integer link_order) {
        this.link_order = link_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_enable
     *
     * @return the value of sy_func_link_mobile.link_is_enable
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_enable() {
        return link_is_enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_enable
     *
     * @param link_is_enable the value for sy_func_link_mobile.link_is_enable
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_enable(Integer link_is_enable) {
        this.link_is_enable = link_is_enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.product_flag
     *
     * @return the value of sy_func_link_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.product_flag
     *
     * @param product_flag the value for sy_func_link_mobile.product_flag
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.link_is_lazeload
     *
     * @return the value of sy_func_link_mobile.link_is_lazeload
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public Integer getLink_is_lazeload() {
        return link_is_lazeload;
    }
    

    public Integer getShow_children_num() {
		return show_children_num;
	}

	public void setShow_children_num(Integer show_children_num) {
		this.show_children_num = show_children_num;
	}

	public Integer getLink_is_show_subcard() {
		return link_is_show_subcard;
	}

	public void setLink_is_show_subcard(Integer link_is_show_subcard) {
		this.link_is_show_subcard = link_is_show_subcard;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.link_is_lazeload
     *
     * @param link_is_lazeload the value for sy_func_link_mobile.link_is_lazeload
     *
     * @mbggenerated Wed May 09 10:29:13 CST 2018
     */
    public void setLink_is_lazeload(Integer link_is_lazeload) {
        this.link_is_lazeload = link_is_lazeload;
    }

	public List<FuncLinkItemMVO> getLinkItems() {
		return linkItems;
	}

	public void setLinkItems(List<FuncLinkItemMVO> linkItems) {
		this.linkItems = linkItems;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link_mobile.sub_func_config
     *
     * @return the value of sy_func_link_mobile.sub_func_config
     *
     * @mbggenerated Wed Jun 26 17:40:44 CST 2019
     */
    public String getSub_func_config() {
        return sub_func_config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link_mobile.sub_func_config
     *
     * @param sub_func_config the value for sy_func_link_mobile.sub_func_config
     *
     * @mbggenerated Wed Jun 26 17:40:44 CST 2019
     */
    public void setSub_func_config(String sub_func_config) {
        this.sub_func_config = sub_func_config == null ? null : sub_func_config.trim();
    }
}