package com.hayden.hap.common.func.entity;

import com.hayden.hap.common.common.entity.BaseVO;

import java.util.List;

public class FuncLinkVO extends BaseVO {

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_id
     *
     * @mbggenerated
     */
    private Long link_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.tenantid
     *
     * @mbggenerated
     */
    private Long tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.main_func_code
     *
     * @mbggenerated
     */
    private String main_func_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.sub_func_code
     *
     * @mbggenerated
     */
    private String sub_func_code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_name
     *
     * @mbggenerated
     */
    private String link_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_where
     *
     * @mbggenerated
     */
    private String link_where;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_control
     *
     * @mbggenerated
     */
    private String link_control;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_del
     *
     * @mbggenerated
     */
    private Integer link_is_del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_update
     *
     * @mbggenerated
     */
    private Integer link_is_update;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_readonly
     *
     * @mbggenerated
     */
    private Integer link_is_readonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_showquery
     *
     * @mbggenerated
     */
    private Integer link_is_showquery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_forward_card
     *
     * @mbggenerated
     */
    private Integer link_is_forward_card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_show_subcard
     *
     * @mbggenerated
     */
    private Integer link_is_show_subcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_order
     *
     * @mbggenerated
     */
    private Integer link_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_func_link.link_is_enable
     *
     * @mbggenerated
     */
    private Integer link_is_enable;
    
    /**
     * 关联字段
     */
    private List<FuncLinkItemVO> linkItems;
    
    /**
     * 子功能所属模块
     */
    private String subModuleCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_func_link
     *
     * @mbggenerated
     */
    public FuncLinkVO() {
        super("SY_FUNC_LINK");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_id
     *
     * @return the value of sy_func_link.link_id
     *
     * @mbggenerated
     */
    public Long getLink_id() {
        return link_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_id
     *
     * @param link_id the value for sy_func_link.link_id
     *
     * @mbggenerated
     */
    public void setLink_id(Long link_id) {
        this.link_id = link_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.tenantid
     *
     * @return the value of sy_func_link.tenantid
     *
     * @mbggenerated
     */
    public Long getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.tenantid
     *
     * @param tenantid the value for sy_func_link.tenantid
     *
     * @mbggenerated
     */
    public void setTenantid(Long tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.main_func_code
     *
     * @return the value of sy_func_link.main_func_code
     *
     * @mbggenerated
     */
    public String getMain_func_code() {
        return main_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.main_func_code
     *
     * @param main_func_code the value for sy_func_link.main_func_code
     *
     * @mbggenerated
     */
    public void setMain_func_code(String main_func_code) {
        this.main_func_code = main_func_code == null ? null : main_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.sub_func_code
     *
     * @return the value of sy_func_link.sub_func_code
     *
     * @mbggenerated
     */
    public String getSub_func_code() {
        return sub_func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.sub_func_code
     *
     * @param sub_func_code the value for sy_func_link.sub_func_code
     *
     * @mbggenerated
     */
    public void setSub_func_code(String sub_func_code) {
        this.sub_func_code = sub_func_code == null ? null : sub_func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_name
     *
     * @return the value of sy_func_link.link_name
     *
     * @mbggenerated
     */
    public String getLink_name() {
        return link_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_name
     *
     * @param link_name the value for sy_func_link.link_name
     *
     * @mbggenerated
     */
    public void setLink_name(String link_name) {
        this.link_name = link_name == null ? null : link_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_where
     *
     * @return the value of sy_func_link.link_where
     *
     * @mbggenerated
     */
    public String getLink_where() {
        return link_where;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_where
     *
     * @param link_where the value for sy_func_link.link_where
     *
     * @mbggenerated
     */
    public void setLink_where(String link_where) {
        this.link_where = link_where == null ? null : link_where.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_control
     *
     * @return the value of sy_func_link.link_control
     *
     * @mbggenerated
     */
    public String getLink_control() {
        return link_control;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_control
     *
     * @param link_control the value for sy_func_link.link_control
     *
     * @mbggenerated
     */
    public void setLink_control(String link_control) {
        this.link_control = link_control == null ? null : link_control.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_del
     *
     * @return the value of sy_func_link.link_is_del
     *
     * @mbggenerated
     */
    public Integer getLink_is_del() {
        return link_is_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_del
     *
     * @param link_is_del the value for sy_func_link.link_is_del
     *
     * @mbggenerated
     */
    public void setLink_is_del(Integer link_is_del) {
        this.link_is_del = link_is_del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_update
     *
     * @return the value of sy_func_link.link_is_update
     *
     * @mbggenerated
     */
    public Integer getLink_is_update() {
        return link_is_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_update
     *
     * @param link_is_update the value for sy_func_link.link_is_update
     *
     * @mbggenerated
     */
    public void setLink_is_update(Integer link_is_update) {
        this.link_is_update = link_is_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_readonly
     *
     * @return the value of sy_func_link.link_is_readonly
     *
     * @mbggenerated
     */
    public Integer getLink_is_readonly() {
        return link_is_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_readonly
     *
     * @param link_is_readonly the value for sy_func_link.link_is_readonly
     *
     * @mbggenerated
     */
    public void setLink_is_readonly(Integer link_is_readonly) {
        this.link_is_readonly = link_is_readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_showquery
     *
     * @return the value of sy_func_link.link_is_showquery
     *
     * @mbggenerated
     */
    public Integer getLink_is_showquery() {
        return link_is_showquery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_showquery
     *
     * @param link_is_showquery the value for sy_func_link.link_is_showquery
     *
     * @mbggenerated
     */
    public void setLink_is_showquery(Integer link_is_showquery) {
        this.link_is_showquery = link_is_showquery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_forward_card
     *
     * @return the value of sy_func_link.link_is_forward_card
     *
     * @mbggenerated
     */
    public Integer getLink_is_forward_card() {
        return link_is_forward_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_forward_card
     *
     * @param link_is_forward_card the value for sy_func_link.link_is_forward_card
     *
     * @mbggenerated
     */
    public void setLink_is_forward_card(Integer link_is_forward_card) {
        this.link_is_forward_card = link_is_forward_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_show_subcard
     *
     * @return the value of sy_func_link.link_is_show_subcard
     *
     * @mbggenerated
     */
    public Integer getLink_is_show_subcard() {
        return link_is_show_subcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_show_subcard
     *
     * @param link_is_show_subcard the value for sy_func_link.link_is_show_subcard
     *
     * @mbggenerated
     */
    public void setLink_is_show_subcard(Integer link_is_show_subcard) {
        this.link_is_show_subcard = link_is_show_subcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_order
     *
     * @return the value of sy_func_link.link_order
     *
     * @mbggenerated
     */
    public Integer getLink_order() {
        return link_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_order
     *
     * @param link_order the value for sy_func_link.link_order
     *
     * @mbggenerated
     */
    public void setLink_order(Integer link_order) {
        this.link_order = link_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_func_link.link_is_enable
     *
     * @return the value of sy_func_link.link_is_enable
     *
     * @mbggenerated
     */
    public Integer getLink_is_enable() {
        return link_is_enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_func_link.link_is_enable
     *
     * @param link_is_enable the value for sy_func_link.link_is_enable
     *
     * @mbggenerated
     */
    public void setLink_is_enable(Integer link_is_enable) {
        this.link_is_enable = link_is_enable;
    }

	public List<FuncLinkItemVO> getLinkItems() {
		return linkItems;
	}

	public void setLinkItems(List<FuncLinkItemVO> linkItems) {
		this.linkItems = linkItems;
	}

	public String getSubModuleCode() {
		return subModuleCode;
	}

	public void setSubModuleCode(String subModuleCode) {
		this.subModuleCode = subModuleCode;
	}
}