package com.hayden.hap.common.upgrade.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class UpgradeFrontVO extends BaseVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.front_config_id
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private Long front_config_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.moudel_code
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String module_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.current_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String current_version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.upgrade_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String upgrade_version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.static_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String static_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.app_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String app_path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.created_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String created_by_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.updated_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private String updated_by_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.isenable
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private Integer isenable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.product_flag
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private Integer product_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mgr_upgrade_front.orgid
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    private Long orgid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mgr_upgrade_front
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public UpgradeFrontVO() {
        super("mgr_upgrade_front");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.front_config_id
     *
     * @return the value of mgr_upgrade_front.front_config_id
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public Long getFront_config_id() {
        return front_config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.front_config_id
     *
     * @param front_config_id the value for mgr_upgrade_front.front_config_id
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setFront_config_id(Long front_config_id) {
        this.front_config_id = front_config_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.moudel_code
     *
     * @return the value of mgr_upgrade_front.moudel_code
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getModule_code() {
        return module_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.moudel_code
     *
     * @param module_code the value for mgr_upgrade_front.moudel_code
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setModule_code(String module_code) {
        this.module_code = module_code == null ? null : module_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.current_version
     *
     * @return the value of mgr_upgrade_front.current_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getCurrent_version() {
        return current_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.current_version
     *
     * @param current_version the value for mgr_upgrade_front.current_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setCurrent_version(String current_version) {
        this.current_version = current_version == null ? null : current_version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.upgrade_version
     *
     * @return the value of mgr_upgrade_front.upgrade_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getUpgrade_version() {
        return upgrade_version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.upgrade_version
     *
     * @param upgrade_version the value for mgr_upgrade_front.upgrade_version
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setUpgrade_version(String upgrade_version) {
        this.upgrade_version = upgrade_version == null ? null : upgrade_version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.static_path
     *
     * @return the value of mgr_upgrade_front.static_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getStatic_path() {
        return static_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.static_path
     *
     * @param static_path the value for mgr_upgrade_front.static_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setStatic_path(String static_path) {
        this.static_path = static_path == null ? null : static_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.app_path
     *
     * @return the value of mgr_upgrade_front.app_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getApp_path() {
        return app_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.app_path
     *
     * @param app_path the value for mgr_upgrade_front.app_path
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setApp_path(String app_path) {
        this.app_path = app_path == null ? null : app_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.created_by_name
     *
     * @return the value of mgr_upgrade_front.created_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getCreated_by_name() {
        return created_by_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.created_by_name
     *
     * @param created_by_name the value for mgr_upgrade_front.created_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setCreated_by_name(String created_by_name) {
        this.created_by_name = created_by_name == null ? null : created_by_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.updated_by_name
     *
     * @return the value of mgr_upgrade_front.updated_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public String getUpdated_by_name() {
        return updated_by_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.updated_by_name
     *
     * @param updated_by_name the value for mgr_upgrade_front.updated_by_name
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setUpdated_by_name(String updated_by_name) {
        this.updated_by_name = updated_by_name == null ? null : updated_by_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.isenable
     *
     * @return the value of mgr_upgrade_front.isenable
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public Integer getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.isenable
     *
     * @param isenable the value for mgr_upgrade_front.isenable
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setIsenable(Integer isenable) {
        this.isenable = isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.product_flag
     *
     * @return the value of mgr_upgrade_front.product_flag
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.product_flag
     *
     * @param product_flag the value for mgr_upgrade_front.product_flag
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mgr_upgrade_front.orgid
     *
     * @return the value of mgr_upgrade_front.orgid
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mgr_upgrade_front.orgid
     *
     * @param orgid the value for mgr_upgrade_front.orgid
     *
     * @mbggenerated Thu Apr 09 17:50:43 CST 2020
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }
}