package com.hayden.hap.common.export.entity;

import com.hayden.hap.common.common.entity.BaseVO;

public class ExportTemplateVO extends BaseVO {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.exportid
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    private Long exportid;
    private Integer is_enable;
    private Integer is_export_linklist;
    
    /**
     * txt导出间隔符
     */
    private String  txt_separator;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.export_temp_code
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
   // private String export_temp_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.export_temp_name
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    private String export_temp_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.func_code
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    private String func_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.file_type
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    private String file_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sy_export_template.product_flag
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    private Integer product_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sy_export_template
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public ExportTemplateVO() {
        super("SY_EXPORT_TEMPLATE");
    }

    public Integer getIs_enable() {
		return is_enable;
	}

	public void setIs_enable(Integer is_enable) {
		this.is_enable = is_enable;
	}

	public Integer getIs_export_linklist() {
		return is_export_linklist;
	}

	public void setIs_export_linklist(Integer is_export_linklist) {
		this.is_export_linklist = is_export_linklist;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.exportid
     *
     * @return the value of sy_export_template.exportid
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public Long getExportid() {
        return exportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template.exportid
     *
     * @param exportid the value for sy_export_template.exportid
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public void setExportid(Long exportid) {
        this.exportid = exportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.export_temp_code
     *
     * @return the value of sy_export_template.export_temp_code
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
//    public String getExport_temp_code() {
//        return export_temp_code;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column sy_export_template.export_temp_code
//     *
//     * @param export_temp_code the value for sy_export_template.export_temp_code
//     *
//     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
//     */
//    public void setExport_temp_code(String export_temp_code) {
//        this.export_temp_code = export_temp_code == null ? null : export_temp_code.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.export_temp_name
     *
     * @return the value of sy_export_template.export_temp_name
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public String getExport_temp_name() {
        return export_temp_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template.export_temp_name
     *
     * @param export_temp_name the value for sy_export_template.export_temp_name
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public void setExport_temp_name(String export_temp_name) {
        this.export_temp_name = export_temp_name == null ? null : export_temp_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.func_code
     *
     * @return the value of sy_export_template.func_code
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public String getFunc_code() {
        return func_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template.func_code
     *
     * @param func_code the value for sy_export_template.func_code
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public void setFunc_code(String func_code) {
        this.func_code = func_code == null ? null : func_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.file_type
     *
     * @return the value of sy_export_template.file_type
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public String getFile_type() {
        return file_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template.file_type
     *
     * @param file_type the value for sy_export_template.file_type
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public void setFile_type(String file_type) {
        this.file_type = file_type == null ? null : file_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sy_export_template.product_flag
     *
     * @return the value of sy_export_template.product_flag
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public Integer getProduct_flag() {
        return product_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sy_export_template.product_flag
     *
     * @param product_flag the value for sy_export_template.product_flag
     *
     * @mbggenerated Wed Sep 14 13:29:52 CST 2016
     */
    public void setProduct_flag(Integer product_flag) {
        this.product_flag = product_flag;
    }

	public String getTxt_separator() {
		return txt_separator;
	}

	public void setTxt_separator(String txt_separator) {
		this.txt_separator = txt_separator;
	}
    
}